### ISSUE TITLE
No matching distribution found for opencv

### ISSUE THREAD

**Issue by ctroupin** [AntSimi/py-eddy-tracker#1]
Hello,

I'm trying to install the eddy tracker and I'm using a virtual environment.
It seems 
```python
pip install opencv
```
should be instead
```python
 pip install opencv-python
```
Can you check? Thanks.

**Comment by AntSimi** [comment]
you are right, i wil modify readme

**Comment by ctroupin** [comment]
Thanks! I have a few minor issues to mention, I prefer to open them separately so it's easier to track.

**Comment by AntSimi** [comment]
ok
