### ISSUE TITLE
question about the filtering

### ISSUE THREAD

**Issue by Xanxus1** [AntSimi/py-eddy-tracker#108]
When I use the method as https://py-eddy-tracker.readthedocs.io/en/latest/grid_load_display.html showed, after the h.bessel_high_filter('adt', 500, order=3), there is no output data, all is "nan". I don't know why and need your help.

**Comment by AntSimi** [comment]
Could you give more informations about your input data?

**Comment by Xanxus1** [comment]
> Could you give more informations about your input data?
I used the example data "nrt_global_allsat_phy_l4_20190223_20190226.nc" in the file directory "py_eddy_tracker\data", which was generated when I install the py-eddy-tracker.

And here is the code I used:

>>> from py_eddy_tracker.dataset.grid import RegularGridDataset
>>> grid_name, lon_name, lat_name = 'D:/Program Files/python38/Lib/site-packages/py_eddy_tracker/data/nrt_global_allsat_phy_l4_20190223_20190226.nc', 'longitude', 'latitude'
>>> h = RegularGridDataset(grid_name, lon_name, lat_name)
We assume pixel position of grid is centered for D:/Program Files/python38/Lib/site-packages/py_eddy_tracker/data/nrt_global_allsat_phy_l4_20190223_20190226.nc
>>> h.bessel_high_filter('adt', 500, order=3)
No filtering above 85.000000 degrees of latitude
>>> h.write('J:/grid1.nc')


No matter in the output file "grid1.nc", or I display directly, there is no data in after the filtering.

So what's the matter with the operation? I don't know why, could you please help me to resolve it?

**Comment by Xanxus1** [comment]
I used the example data "nrt_global_allsat_phy_l4_20190223_20190226.nc" in the file directory "py_eddy_tracker\data", which was generated when I install the py-eddy-tracker.

And here is the code I used:

from py_eddy_tracker.dataset.grid import RegularGridDataset
grid_name, lon_name, lat_name = 'D:/Program Files/python38/Lib/site-packages/py_eddy_tracker/data/nrt_global_allsat_phy_l4_20190223_20190226.nc', 'longitude', 'latitude'
h = RegularGridDataset(grid_name, lon_name, lat_name)
We assume pixel position of grid is centered for D:/Program Files/python38/Lib/site-packages/py_eddy_tracker/data/nrt_global_allsat_phy_l4_20190223_20190226.nc
h.bessel_high_filter('adt', 500, order=3)
No filtering above 85.000000 degrees of latitude
h.write('J:/grid1.nc')

No matter in the output file "grid1.nc", or I display directly, there is no data in after the filtering.

So what's the matter with the operation? I don't know why, could you please help me to resolve it?

&nbsp;

施伟安
厦门大学海洋与地球学院物理海洋系
18级硕士研究生
Tel.18359268393




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 凌晨3:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AntSimi/py-eddy-tracker] question about the filtering (#108)





 
Could you give more informations about your input data?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Xanxus1** [comment]
I used the example data "nrt_global_allsat_phy_l4_20190223_20190226.nc" in the file directory "py_eddy_tracker\data", which was generated when I install the py-eddy-tracker.

And here is the code I used:

from py_eddy_tracker.dataset.grid import RegularGridDataset
grid_name, lon_name, lat_name = 'D:/Program Files/python38/Lib/site-packages/py_eddy_tracker/data/nrt_global_allsat_phy_l4_20190223_20190226.nc', 'longitude', 'latitude'
h = RegularGridDataset(grid_name, lon_name, lat_name)
We assume pixel position of grid is centered for D:/Program Files/python38/Lib/site-packages/py_eddy_tracker/data/nrt_global_allsat_phy_l4_20190223_20190226.nc
h.bessel_high_filter('adt', 500, order=3)
No filtering above 85.000000 degrees of latitude
h.write('J:/grid1.nc')

No matter in the output file "grid1.nc", or I display directly, there is no data in after the filtering.

So what's the matter with the operation? I don't know why, could you please help me to resolve it?









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AntSimi/py-eddy-tracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 凌晨3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AntSimi/py-eddy-tracker] question about the filtering (#108)





 
Could you give more informations about your input data?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AntSimi** [comment]
I am not able to reproduce your error, when i run the following code on [binder](https://mybinder.org/v2/gh/AntSimi/py-eddy-tracker/master?urlpath=lab/tree/notebooks/python_module/), all things works.

```python
from py_eddy_tracker.dataset.grid import RegularGridDataset
from py_eddy_tracker import data
from matplotlib import pyplot as plt

h = RegularGridDataset(
    data.get_demo_path("nrt_global_allsat_phy_l4_20190223_20190226.nc"),
    "longitude",
    "latitude",
)

fig = plt.figure(figsize=(13, 5))
ax = fig.add_axes([0.03, 0.03, 0.90, 0.94])
ax.set_aspect("equal")
mappable = h.display(ax, 'adt', vmin=-1, vmax=1)
ax.grid()
plt.colorbar(mappable, cax=ax.figure.add_axes([0.95, 0.05, 0.01, 0.9]))

h.bessel_high_filter('adt', 500, order=3)

fig = plt.figure(figsize=(13, 5))
ax = fig.add_axes([0.03, 0.03, 0.90, 0.94])
ax.set_aspect("equal")
mappable = h.display(ax, 'adt', vmin=-.1, vmax=.1)
ax.grid()
plt.colorbar(mappable, cax=ax.figure.add_axes([0.95, 0.05, 0.01, 0.9]))
```

**Comment by Xanxus1** [comment]
When I run the same code you give in the biner, it shows the right results.
But when I run it in my PC, it break down. So it confused me with this.
I use the python 3.9.9, and all the packages are the latest.
Is there any request for the version of python or other packages?







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AntSimi/py-eddy-tracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 晚上7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AntSimi/py-eddy-tracker] question about the filtering (#108)





 
I am not able to reproduce your error, when i run the following code on binder, all things works.
 from py_eddy_tracker.dataset.grid import RegularGridDataset from py_eddy_tracker import data from matplotlib import pyplot as plt h = RegularGridDataset(     data.get_demo_path("nrt_global_allsat_phy_l4_20190223_20190226.nc"),     "longitude",     "latitude", ) fig = plt.figure(figsize=(13, 5)) ax = fig.add_axes([0.03, 0.03, 0.90, 0.94]) ax.set_aspect("equal") mappable = h.display(ax, 'adt', vmin=-1, vmax=1) ax.grid() plt.colorbar(mappable, cax=ax.figure.add_axes([0.95, 0.05, 0.01, 0.9])) h.bessel_high_filter('adt', 500, order=3) fig = plt.figure(figsize=(13, 5)) ax = fig.add_axes([0.03, 0.03, 0.90, 0.94]) ax.set_aspect("equal") mappable = h.display(ax, 'adt', vmin=-.1, vmax=.1) ax.grid() plt.colorbar(mappable, cax=ax.figure.add_axes([0.95, 0.05, 0.01, 0.9]))
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AntSimi** [comment]
Binder run use python 3.7
