### ISSUE TITLE
longitudes < than 0 and > than 360  in TrackEddiesObservations

### ISSUE THREAD

**Issue by koldunovn** [AntSimi/py-eddy-tracker#11]
Hi @AntSimi 

I now succesfully run one year of eddy tracking and was able to get `Anticyclonic.nc` and `Cyclonic.nc` files. I load them with:

```
a = TrackEddiesObservations.load_file("./Anticyclonic.nc")
c = TrackEddiesObservations.load_file("./Cyclonic.nc")
```

And the result of
```
print(a.longitude.min())
print(a.longitude.max())
```
is:
```
 -14.2
373.8
```
do I understand it right that it's just a peculiarity of the algorithm, that when the track crosses 0 or 360 it just continues?

Maybe somehow related to this, the `plot` for global data generates something like this:

```python
fig = plt.figure(figsize=(12, 5))
ax = fig.add_axes((0.05, 0.1, 0.9, 0.9))
ax.set_aspect("equal")
ax.set_xlim(-30, 390), ax.set_ylim(-80, 80)
# a.plot(ax, ref=-10, label="Anticyclonic", color="r", lw=0.1)
c.plot(ax, ref=0, label="Cyclonic", color="b", lw=1.1)
ax.legend()
ax.grid()
```

![image](https://user-images.githubusercontent.com/3407313/85037174-497e4480-b185-11ea-8629-91b1706abd54.png)

If I use `ref=None` everything is fine:

```ptyhon
fig = plt.figure(figsize=(12, 5))
ax = fig.add_axes((0.05, 0.1, 0.9, 0.9))
ax.set_aspect("equal")
ax.set_xlim(-30, 390), ax.set_ylim(-80, 80)
# a.plot(ax, ref=-10, label="Anticyclonic", color="r", lw=0.1)
c.plot(ax, ref=None, label="Cyclonic", color="b", lw=1.1)
ax.legend()
ax.grid()
```

![image](https://user-images.githubusercontent.com/3407313/85039287-daeeb600-b187-11ea-80bc-cc4209d770a7.png)

**Comment by AntSimi** [comment]
# 1 how longitude is stored
**Detection** : when we detect eddy longitude of center are force between 0° to 360° [in code](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/dataset/grid.py#L887), and longitude of contour are around center (+-180°).
=> you could have some longitude of contour lower than 0° or bigger than 360°.
NB : if it 's possible wrapping of regular grid is done automatically.

**Tracking** : Before to build file, we apply a function in case of virtual (filled_by_interpolation), which will force longitude around the first position of the track (+-180°), [here in code](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/observations/tracking.py#L103).
=> Longitude of track will be continuous without jump. So you could have longitude again bigger than 360° and lower than 0°.
Maybe i will extend this behavior, when we didn't use virtual.

# 2 Display
The display problem is created by [this line](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/observations/tracking.py#L370), but i didn't what is the good way to do for global file:

1. in some case you may want  just shift some track to display by example ]-180:180] inplace of ]0:360] => in this case maybe i must code a function to cut track when they are on bounds
2. Or you could want have continuous track and display on more than 360°
3. Also we could choose the range based on xlim of axes, but if we do this xlim must be set before the plot function.

I don't what is the best things

# 3 Note for tracking

I don't know, which type of tracking did you select, but the [Default method of tracking](https://py-eddy-tracker.readthedocs.io/en/latest/run_tracking.html#default-method) is not very accurate especially for little eddies. It could create jump between eddies in same track.

**Comment by koldunovn** [comment]
Thanks a lot for clarification - I now know that it's not something strange, but is expected. 

I think there is no simple solution for plotting if one wants to stay simple, and the current way for global data if perfectly fine when you know what `ref` means, and that one should have it as `None` for global data. For the final (publication) plots, one might use cartopy, that should handle the tracks going on the "other side" of the globe, but just have to be careful to adjust longitude coordinates. 

## Tracking
I use the default one. I thought that Mason et al., 2014 method is more advanced than Chelton et al. 2011 :) Do you think for global data it is better to use Chelton et al. 2011?

**Comment by AntSimi** [comment]
Default tracking, are slightly different than describe in Mason et al., 2014.
A method based on contour overlaps (intern or extern) seem to be more robust like [Chaigneau & al](https://doi.org/10.1016/j.pocean.2009.07.012).
Overlaps method could be worse when time sampling is low, but daily sampling is well.
The principal default with chelton method is value used for research area, which allow big jump.

An implementation of overlap method could be found [here](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/featured_tracking/area_tracker.py). Note this implementation used external contour and select every overlap, without reject tiny overlap.

**Comment by koldunovn** [comment]
I probably confuse identification and tracking :)

Thanks for the explanations and suggestions! I will use `CheltonTracker` then.
