### ISSUE TITLE
Observation Flag

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#110]
Dear Antoine,

Could you please help me in understanding how the “observation_flag” is used in the code?

Thanks…

**Comment by AntSimi** [comment]
Hi,

`observation_flag` is an output of tracking:

- 0 -> is a detected eddy
- 1 -> is a missing eddy, which allow to put together several detected eddy, this value appear when you use VIRTUAL in tracking

**Comment by Ashwita2619** [comment]
My concern is:
why I don't see the flag = 1, even when I am using the Virtual length in the tracking?
where, I see the differences with different virtual lengths: 1, 2, or 3
but I don't see the flag = 1, when I am trying to see it in the map!

Could you please help me with this?

**Comment by AntSimi** [comment]
if you want more help maybe share data or/and graph to show problems

**Comment by Ashwita2619** [comment]
[Anticyclonic_VL01.nc.zip](https://github.com/AntSimi/py-eddy-tracker/files/7245436/Anticyclonic_VL01.nc.zip)
[Cyclonic_VL01.nc.zip](https://github.com/AntSimi/py-eddy-tracker/files/7245438/Cyclonic_VL01.nc.zip)
[Anticyclonic_VL03.nc.zip](https://github.com/AntSimi/py-eddy-tracker/files/7245439/Anticyclonic_VL03.nc.zip)
[Cyclonic_VL03.nc.zip](https://github.com/AntSimi/py-eddy-tracker/files/7245440/Cyclonic_VL03.nc.zip)


<img width="1383" alt="T5V1_T5V3" src="https://user-images.githubusercontent.com/53576269/135114485-57ae0d91-d6c6-4eff-a5af-9e1d9c8f33e2.png">

I have attached the tracked files: with virtual length (VL) of 1 day and 3 days, and minimum track duration of 5 days.
The tracking is done along isopycnal 27.86

The figure attached above shows the tracked eddies (at one time step)
the differences are highlighted with the green ellipses 
here, in the attached plot I tried to see the structures with flag = 1
but, we see nothing
whereas, if I choose to look for flag = 0, I see the whole map with detected eddies…

**Comment by AntSimi** [comment]
Ok quick answers,
Flagged observation(virtual) haven't contour, you could fill those contours [with this function](with https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/observations/observation.py#L439) if you use python module.
I will look to the data later

**Comment by AntSimi** [comment]
Flag looks good.
I looked at some contours, their shape seems very irregular, are you happy with that?

**Comment by Ashwita2619** [comment]
The contour definition is okay for me.
But, I unable to see the flagged (flag=1) contour

**Comment by AntSimi** [comment]
Here, some examples to show virtual, i hope it will help you

```python
from py_eddy_tracker.observations.tracking import TrackEddiesObservations
from matplotlib import pyplot as plt
from py_eddy_tracker import gui
```


```python
# Load data
anticyclonic = TrackEddiesObservations.load_file('Anticyclonic_VL01.nc')
```

# Display percent of virtual
```python
def start_axes(title):
    fig = plt.figure(figsize=(8, 8))
    ax = fig.add_axes([0.03, 0.03, 0.90, 0.94], projection='full_axes')
    ax.set_xlim(-100, 20), ax.set_ylim(-70, 70)
    ax.set_aspect("equal")
    ax.set_title(title)
    return ax
```


```python
# Compute percent of virtual/flaged observations by box
step = 2
g = anticyclonic.grid_stat(((-100, 20, step), (-70, 70, step)), "virtual")
g.vars["virtual"] *= 100
```


```python
ax = start_axes("Percent of virtual by box of %s°" % step)
m = g.display(ax, name="virtual", vmin=0, vmax=20)
ax.grid()
cb = plt.colorbar(m, cax=ax.figure.add_axes([0.94, 0.05, 0.01, 0.9]))
cb.set_label("Percent of virtual (%)")
```

![output_4_0](https://user-images.githubusercontent.com/36040805/135520871-25f0fe0a-1e5e-444b-a6f5-af58a1d863f4.png)

# Display virtual/flagged observations for one track

```python
# Compute number of virtual by track
i_track_max = anticyclonic.count_by_track(anticyclonic.observation_flag).argmax()
# Get track id for track which contains the highest number of virtual
track = anticyclonic.first_obs().track[i_track_max]
# Extract selected track
selected_track = anticyclonic.extract_ids([track])
```


```python
fig = plt.figure(figsize=(10,8))
ax = fig.add_subplot(111)
m = selected_track.filled(ax, 'time', cmap='Spectral_r', alpha=.35)
plt.colorbar(m)
selected_track.plot(ax)
# Yellow scatter => virtual/flagged obs
# Blue scatter => detected eddies
selected_track.scatter(ax, 'observation_flag',s=60)
ax.set_xlim(306.4,307)
ax.set_ylim(12.6,13.1)
ax.grid()
ax.set_aspect('equal')
```
![output_6_0](https://user-images.githubusercontent.com/36040805/135520890-dc29b5a8-370c-41f3-b7d5-97d73e702931.png)
