### ISSUE TITLE
New SLA netcdf format,  filter doesn't work

### ISSUE THREAD

**Issue by SusanaMSilva** [AntSimi/py-eddy-tracker#111]
Hi.

I'm using your codes to filter SLA data, but it doesn't work with the new SLA data netcdf format provided by Copernicus Marine Service. I already used your codes in a previous work and it worked perfectly with the old netcdf files. Can you help me with this problem?  

Thank you

**Comment by AntSimi** [comment]
How did you get input data?
When i look with `ncdump`, i saw variable type in double&float which are not original format.

A quick answer could be to create mask like here :
```python
from netCDF4 import Dataset
from matplotlib import pyplot as plt
from py_eddy_tracker.dataset.grid import RegularGridDataset
import numpy as np
```


```python
h = Dataset('dataset-duacs-rep-global-merged-allsat-phy-l4_1633015461903.nc')
```


```python
# File have nan and mask ...
h.variables['sla'][:]
```




    masked_array(
      data=[[[nan, nan, nan, ..., nan, nan, nan],
             [nan, nan, nan, ..., nan, nan, nan],
             [nan, nan, nan, ..., nan, nan, nan],
             ...,
             [nan, nan, nan, ..., nan, nan, nan],
             [nan, nan, nan, ..., nan, nan, nan],
             [nan, nan, nan, ..., nan, nan, nan]]],
      mask=False,
      fill_value=1e+20)




```python
grid_name, lon_name, lat_name = 'dataset-duacs-rep-global-merged-allsat-phy-l4_1633015461903.nc', 'longitude', 'latitude'
g = RegularGridDataset(grid_name, lon_name, lat_name)
```


```python
g.display(ax=plt.subplot(111), name='sla')
```


    
![output_4_0](https://user-images.githubusercontent.com/36040805/137801924-e7ab91ef-831d-4bee-9ae2-3b0d57bdd223.png)
  



```python
g.copy('sla', 'sla_filt1')
```


```python
# Try filtering raw data ...
g.bessel_high_filter('sla_filt1', 500, order=1)
m =g.display(ax=plt.subplot(111), name='sla_filt1', vmin=-.15, vmax=.15)
plt.colorbar(m)
```


![output_6_1](https://user-images.githubusercontent.com/36040805/137801953-a2f0afe2-7980-4a0a-9322-d7857b1132ab.png)


```python
# Try filtering modified data we create a mask with isnan function
g.copy('sla', 'sla_filt2')
d = g.vars['sla_filt2']
g.vars['sla_filt2'] = np.ma.array(d, mask=np.isnan(d))
```


```python
g.bessel_high_filter('sla_filt2', 500, order=1)
m =g.display(ax=plt.subplot(111), name='sla_filt2', vmin=-.15, vmax=.15)
plt.colorbar(m)
```


![output_8_1](https://user-images.githubusercontent.com/36040805/137801975-d68aab4e-7aa2-441f-9fa0-0bd3fb8454e4.png)
