### ISSUE TITLE
equatorial eddies Detect

### ISSUE THREAD

**Issue by l1uw3n** [AntSimi/py-eddy-tracker#120]
Hello, I want to plot the eddies of the equator. Which method is better for vortex? Is the ADT method not applicable?

**Comment by AntSimi** [comment]
Hi,
Question is too open to answer correctly.
Py eddy tracker software could produce eddies detection at equator (~+/-5°), but assumption of geostrophic current computed from height with derivation is not good.
And ADT field must be prefered to SLA for reasons explained in https://essd.copernicus.org/preprints/essd-2021-300/ (Figure 6).
