### ISSUE TITLE
Issues with using py-eddy-tracker in Python

### ISSUE THREAD

**Issue by cloemueller** [AntSimi/py-eddy-tracker#124]
Hello, 
I am a student at Hunter College and I wanted to use PyEddyTracker to identify eddies in the Caribbean Sea, specifically for my thesis work. I received help from a MA in Geo-informatics, but several issues arose that we thought were worth bringing to your attention.
We tried to import the PyEddyTracker package into Visual Studio using Python version 3.9. It kept giving an error when importing the dependencies, particularly with Polygon3. We tried downloading Polygon3 on its own, but then there were still other issues. We even tried using older Python versions (Python 3.4) and that did not work either. In the end, we downloaded the entire repository from GitHub and started hosting it on our own GitHub repository so that we could add our own data and then use Binder notebook to use the PyEddyTracker products. This worked, but using binder is slow and Binder also did not give us full access to some of the products because you can't make changes to the code directly on Binder, just run the code. We also were not able to write files through Binder, so we could not build the cyclonic/anticyclonic data sets. If we were able to do it through Python directly, we would have truly been able to use all of the products in PyEddyTracker, which why we suggest updating your code to be more current. It's an amazing product and we really hope to be able to work with it more fully in the future!

**Comment by AntSimi** [comment]
Hello,

I guess you work on windows, i am not familiar with it.
But at each commit we run test on 2 platforms Ubuntu and Windows for latest python 3.7, 3.8, 3.9 (minimal needs 3.7).
polygon3 installation work for every version with pip.
How did you create your python env and how did you install your packages?
Did you try installation from scratch?
[Test configuration](https://github.com/AntSimi/py-eddy-tracker/blob/master/.github/workflows/python-app.yml)

If you have ideas, suggestions or contributions, all are welcome!

Antoine

**Comment by cloemueller** [comment]
![IMG_20220112_151202876_HDR](https://user-images.githubusercontent.com/96787610/149215114-a210442d-7b66-4dc1-bb9b-376ee800ec68.jpg)

I tried it again from scratch and here is the preview of the errors we continue to get. Please let me know what you think.

**Comment by AntSimi** [comment]
When you run pip install polygon3 did you have same result?

**Comment by cloemueller** [comment]
Yes, we ran it multiple times on different computers and got the same result each time.

**Comment by AntSimi** [comment]
Ok to build this package (Polygon3), your computer  need an updated version of visual c++, like it's describe in the error message.
You could also get a wheel on an unofficial site [like explain here](https://github.com/QuTech-Delft/qtt/issues/579#issuecomment-501581980).
Wheel are already compiled, it avoid some problem of compilation.
