### ISSUE TITLE
Plotting time series of eddy

### ISSUE THREAD

**Issue by Sheveenah** [AntSimi/py-eddy-tracker#126]
Good morning Antoine, 
I wanted to confirm something with you.
Say I tracked my eddies for a period of 20 years, and I want to generate a time series for a small box which would show me when an eddy is occurring, and when it is not for that whole time period, 

Can I plot speed average v/s time? or latitude eddy centre v/s time?
Or which variable is more appropriate to you to plot to show that result of occurrence of eddies?

Also, is there a way from the anticyclonic.nc file whereby I can cut a small box from it, and plot the latitude v/s time?

Sorry if my question sounds so vague or not well explained. 
Have a beautiful day
Sheveenah Taukoor

**Comment by AntSimi** [comment]
Did you take look at this [gallery](https://py-eddy-tracker.readthedocs.io/en/stable/python_module/index.html#tracking-diagnostics)?

**Comment by Sheveenah** [comment]
Yes I did, 
although I'm not sure I'm finding my answer there... 
I get the feeling some of these plots are focused on one eddy track... or maybe I am wrong... 
While I want to focus on a small geographic box and generate a time series of all the eddies in that region so that later I can use it as correlation against another thing. 

thoughts? :)

**Comment by AntSimi** [comment]
[I add this example](https://py-eddy-tracker--127.org.readthedocs.build/en/127/python_module/02_eddy_identification/pet_statistics_on_identification.html#sphx-glr-python-module-02-eddy-identification-pet-statistics-on-identification-py), is it close of your needs?
The 2 last figures show difference between count eddies presence in a box and compute percent of area occupy by eddies
