### ISSUE TITLE
beginner issue

### ISSUE THREAD

**Issue by Kris-wu-glut** [AntSimi/py-eddy-tracker#13]
hi,i justI just started to study the ocean eddies,I want to know what the two circles of the eddies represent respectively.
![1](https://user-images.githubusercontent.com/66007137/86090847-6dbf1700-badd-11ea-8ff4-a3b99016d8ab.png)

**Comment by AntSimi** [comment]
dashed line => effective contour
solid line => speed contour
For more information look at Figure 1 at the reference paper of py-eddy-tracker https://doi.org/10.1175/JTECH-D-14-00019.1

**Comment by Kris-wu-glut** [comment]
thanks, it helped me a lot.

**Comment by RandomlyHuman** [comment]
Sorry to reopen this question, but I reviewed the recommendation guidance document, but it is not very clear to me, so which of the two would delimit the eddie, the effective contour 'contour_lat_e' or the speed contour 'contour_lat_s'? Sorry I'm trying to learn a little more.

**Comment by RandomlyHuman** [comment]
> dashed line => effective contour solid line => speed contour For more information look at Figure 1 at the reference paper of py-eddy-tracker https://doi.org/10.1175/JTECH-D-14-00019.1

Sorry to reopen this question, but I reviewed the recommendation guidance document, but it is not very clear to me, so which of the two would delimit the eddie, the effective contour 'contour_lat_e' or the speed contour 'contour_lat_s'? Sorry I'm trying to learn a little more.
