### ISSUE TITLE
No response occurred after executing the tests program

### ISSUE THREAD

**Issue by limaolin1981611** [AntSimi/py-eddy-tracker#130]
I have run the test_grid.py .etc tests program, but no response occurred, only showed as follows:

C:\Users\Apple\anaconda3\python.exe D:/Project/MesoscaleEddy/python/py-eddy-tracker-master/tests/test_grid.py
We assume pixel position of grid is centered for C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.9.egg\py_eddy_tracker\data\mask_1_60.nc

Process finished with exit code 0

What's wrong?

**Comment by AntSimi** [comment]
All code/test in https://github.com/AntSimi/py-eddy-tracker/tree/master/tests are there to check code behaviour, there is no output.
These tests can be run with `pytest -vv` when you are in py eddy tracker folder
If you search example search [in gallery]() or [in this folder](https://github.com/AntSimi/py-eddy-tracker/tree/master/examples)

**Comment by limaolin1981611** [comment]
Thanks，After I used "plt.show()", there were figs.
Another question, I run the pet_eddy_detection.py, Detected Eddies fig as follows, is it right
![Figure_10](https://user-images.githubusercontent.com/62914884/152084699-71df4545-2091-4d02-a1f8-1d21a6e15bb9.png)
?

**Comment by limaolin1981611** [comment]
I run all the pet_eddy_**.py, Detected Eddies fig as follows, what's wrong
![Figure_1](https://user-images.githubusercontent.com/62914884/152153398-dd99022d-37e6-452c-a772-ed944487dd63.png)
?

**Comment by AntSimi** [comment]
I checked this example with current py eddy tracker version on notebook and python console.
I was not able to reproduce your problem.

I will need some basics information:
- Which version of py-eddy-tracker did you use?
- Which version of matplotlib did you use?
- Which version of numba/numpy did you use?
- How did you run examples?
- Did you add some modifications?

Could you build a [minimal reproductible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by limaolin1981611** [comment]
1.the newest version of py-eddy-tracker
2.matplotlib  3.4.3
3.numba/numpy  0.54.1/1.20.3
4.run the example in Anaconda  python 3.9.7
5.not modification
[02_eddy_identification.zip](https://github.com/AntSimi/py-eddy-tracker/files/7990126/02_eddy_identification.zip)

**Comment by AntSimi** [comment]
When you run the following code:
```python
from matplotlib import pyplot as plt
from py_eddy_tracker import data
from py_eddy_tracker.observations.observation import EddiesObservations

def start_axes(title):
    fig = plt.figure(figsize=(13, 5))
    ax = fig.add_axes([0.03, 0.03, 0.90, 0.94])
    ax.set_aspect("equal")
    ax.set_title(title, weight="bold")
    return ax

a = EddiesObservations.load_file(data.get_demo_path("Anticyclonic_20160515.nc"))

ax = start_axes("Detected Eddies")
a.display(ax, color="r", label="Anticyclonic ({nb_obs} eddies)", ref=-10)
ax.legend()
ax.grid()
```

Did you have the following output?
![téléchargement](https://user-images.githubusercontent.com/36040805/152504767-a255010e-00d4-4999-b891-46d5c98e63c2.png)

**Comment by limaolin1981611** [comment]
yes !
![Figure_1](https://user-images.githubusercontent.com/62914884/152523261-1decf2ae-2f5e-4901-af60-8b5686b4c3fb.png)

**Comment by limaolin1981611** [comment]
The figs of the files in “data” are correct.
But, the Anticyclonic and Cyclonic files of my code are wrong.

**Comment by limaolin1981611** [comment]
when I "pip install polygon3", there were errors as follows"Microsoft Visual C++ 14.0 is required". I first installed "VisualCppBuildTools_Full", then "pip install polygon3".

**Comment by AntSimi** [comment]
> when I "pip install polygon3", there were errors as follows"Microsoft Visual C++ 14.0 is required". I first installed "VisualCppBuildTools_Full", then "pip install polygon3".

Did you succed to install polygon3?

**Comment by AntSimi** [comment]
If you run this minimal reproductible example:
```python
from matplotlib import pyplot as plt
from py_eddy_tracker import data
from py_eddy_tracker.dataset.grid import RegularGridDataset
from datetime import datetime

g = RegularGridDataset(data.get_demo_path("dt_med_allsat_phy_l4_20160515_20190101.nc"), "longitude", "latitude")
g.add_uv("adt")
g.bessel_high_filter("adt", 500)
a, c = g.eddy_identification("adt", "u", "v", datetime(2016, 5, 15), 0.002, shape_error=55)

ax = plt.figure(figsize=(13, 5)).add_axes([0.03, 0.03, 0.90, 0.94])
ax.set_aspect("equal")
a.display(ax, color="r", label="Anticyclonic ({nb_obs} eddies)", ref=-10)
ax.legend()
ax.grid()
```
Did you get this result:
![image](https://user-images.githubusercontent.com/36040805/152532029-3ccdf13d-e0a6-4f94-9d6c-dc910d16ec8e.png)

**Comment by limaolin1981611** [comment]
polygon3 3.0.9.1

**Comment by limaolin1981611** [comment]
n
![Figure_1](https://user-images.githubusercontent.com/62914884/152532495-026cb06a-5416-4fdd-b339-fa1b8d6bc176.png)
o

**Comment by AntSimi** [comment]
Could you give the output of this:
```python
from py_eddy_tracker import data
from py_eddy_tracker.dataset.grid import RegularGridDataset
from datetime import datetime
from py_eddy_tracker.generic import flatten_line_matrix, wrap_longitude

g = RegularGridDataset(data.get_demo_path("dt_med_allsat_phy_l4_20160515_20190101.nc"), "longitude", "latitude")
g.add_uv("adt")
g.bessel_high_filter("adt", 500)
a, c = g.eddy_identification("adt", "u", "v", datetime(2016, 5, 15), 0.002, shape_error=55)

lat_s = flatten_line_matrix(a.contour_lat_s)
lon_s = flatten_line_matrix(a.contour_lon_s)
lon_s, lat_s = wrap_longitude(lon_s, lat_s, ref=-10, cut=True)
print(lon_s[:150])
print(lat_s[:150])
```

**Comment by limaolin1981611** [comment]
We assume pixel position of grid is centered for C:\Users\Apple\anaconda3\lib\site-packages\pyeddytracker-0+unknown-py3.9.egg\py_eddy_tracker\data\dt_med_allsat_phy_l4_20160515_20190101.nc
[  28.1875    -331.7939             nan  388.1875      28.206074
   28.215363    28.243223    28.252512    28.28966     28.308235
   28.317406    28.40813     28.413164    28.418884    28.424603
   28.43032     28.430279    28.401947    28.387781    28.373615
   28.345285    28.338814    28.321371    28.312649    28.303345
   28.256773    28.247458   388.19156            nan -331.75253
   28.191559    28.182281    28.11734     28.098785    28.070953
   28.061768    28.053375    28.046326    27.977844    27.94046
   27.934204    27.915192    27.919281    27.932037    27.938507
   27.97403     27.98825     28.030853    28.059265    28.066925
   28.091248    28.099518    28.134705    28.143494    28.169891
   28.1875             nan    4.9375       4.947826     4.9575014
    5.003118     5.0122414    5.057858     5.0661697    5.110993
    5.1259336    5.1632867    5.168686     5.1418295    5.1373534
    5.092593     5.085762     5.0672336    5.057787     5.038513
    5.0096025    4.9999657    4.971055     4.9421444    4.9320445
    4.879391   364.81622            nan -355.1206       4.816223
    4.805908     4.7753296    4.744751     4.6937866    4.683655
    4.6236877    4.613678     4.5737       4.5671997    4.583618
    4.6164246    4.6197205    4.6250916    4.633362     4.6829834
    4.6918945    4.721039     4.769623     4.7793274    4.8084717
    4.8178406 -355.12732            nan  364.81784      4.8726916
    4.9092517    4.9275317    4.9375             nan   20.5625
   20.588778    20.615053    20.623812    20.658848    20.685125
   20.693892    20.711433    20.737745    20.746515    20.772827
   20.807909    20.814312    20.82572     20.829422    20.818045
   20.812376    20.72902     20.72462     20.712582    20.699038
   20.695913    20.688726    20.684458    20.66136     20.64288
   20.62902     20.610542    20.60365     20.568012    20.56114
   20.531115    20.52685     20.495213    20.483349    20.455666 ]
[33.91166  33.912666       nan 33.91166  33.912666 33.91317  33.91468
 33.915184 33.9172   33.918205 33.919373 33.936653 33.941406 33.979733
 34.01806  34.056385 34.063847 34.103813 34.1238   34.143784 34.183754
 34.188705 34.194225 34.196987 34.19758  34.200344 34.200897 34.20422
       nan 34.200897 34.20422  34.203968 34.197803 34.19604  34.193398
 34.19229  34.188858 34.18402  34.12074  34.086224 34.080513 34.06351
 34.05787  34.046597 34.041054 34.016068 34.006073 33.976093 33.956104
 33.95176  33.94034  33.93686  33.926777 33.92426  33.9167   33.91166
       nan 41.81054  41.811882 41.814587 41.833843 41.837696 41.856956
 41.861614 41.894543 41.90552  41.932964 41.938725 41.981144 41.988213
 42.058907 42.064323 42.07174  42.075172 42.081467 42.090908 42.09406
 42.1035   42.11294  42.114536 42.115295 42.116203       nan 42.115295
 42.116203 42.114983 42.109097 42.103207 42.09339  42.091244 42.07655
 42.0741   42.064304 42.060547 42.023434 41.94921  41.941788 41.935467
 41.93065  41.901752 41.89778  41.888916 41.87414  41.87119  41.862324
 41.858856 41.835876       nan 41.858856 41.835876 41.820557 41.812897
 41.81054        nan 33.785137 33.78343  33.78172  33.78115  33.77887
 33.777164 33.77732  33.778175 33.779457 33.779884 33.781166 33.78288
 33.786236 33.80599  33.81256  33.823692 33.829273 33.932335 33.93857
 33.996128 34.060883 34.06767  34.081005 34.08738  34.118484 34.143368
 34.162033 34.186916 34.191406 34.212955 34.215076 34.188313 34.18196
 34.12974  34.11016  34.06447 ]

**Comment by AntSimi** [comment]
Oups
```python
lat_s = flatten_line_matrix(a.contour_lat_s)
lon_s = flatten_line_matrix(a.contour_lon_s)
print(lon_s[:10])
lon_s, lat_s = wrap_longitude(lon_s, lat_s, ref=-10, cut=True)
print(lon_s[:10])
```
This must return that:
```
[28.1875   28.206074 28.233936 28.271086 28.308235 28.317406 28.344624
 28.371841 28.40813  28.413164]
[28.1875   28.206074 28.233936 28.271086 28.308235 28.317406 28.344624
 28.371841 28.40813  28.413164]
```

**Comment by limaolin1981611** [comment]
[388.1875    28.206074  28.215363  28.243223  28.252512  28.28966
  28.308235  28.317406  28.40813   28.413164]
[  28.1875   -331.7939           nan  388.1875     28.206074   28.215363
   28.243223   28.252512   28.28966    28.308235]

**Comment by limaolin1981611** [comment]
output of this

from py_eddy_tracker import data
from py_eddy_tracker.dataset.grid import RegularGridDataset
from datetime import datetime
from py_eddy_tracker.generic import flatten_line_matrix, wrap_longitude

g = RegularGridDataset(data.get_demo_path("dt_med_allsat_phy_l4_20160515_20190101.nc"), "longitude", "latitude")
g.add_uv("adt")
g.bessel_high_filter("adt", 500)
a, c = g.eddy_identification("adt", "u", "v", datetime(2016, 5, 15), 0.002, shape_error=55)

lat_s = flatten_line_matrix(a.contour_lat_s)
lon_s = flatten_line_matrix(a.contour_lon_s)
print(lon_s[:10])
lon_s, lat_s = wrap_longitude(lon_s, lat_s, ref=-10, cut=True)
print(lon_s[:10])

**Comment by AntSimi** [comment]
Could you return the result of that
```python
from numpy import array, isnan, empty, nan
from numba import njit

@njit
def wrap_longitude(x, y, ref, cut=False):
    if cut:
        indexs = list()
        nb = x.shape[0]
        new_previous = (x[0] - ref) % 360
        x_previous = x[0]
        for i in range(1, nb):
            x_ = x[i]
            new_x = (x_ - ref) % 360
            if not isnan(x_) and not isnan(x_previous):
                d_new = new_x - new_previous
                d = x_ - x_previous
                print(i, d_new, d)
                if abs(d - d_new) > 1e-5:
                    indexs.append(i)
            x_previous, new_previous = x_, new_x
        print(indexs)
        nb_indexs = len(indexs)
        new_size = nb + nb_indexs * 3
        out_x = empty(new_size, dtype=x.dtype)
        out_y = empty(new_size, dtype=y.dtype)
        i_ = 0
        j = 0
        for i in range(nb):
            if j < nb_indexs and i == indexs[j]:
                j += 1
                cor = 360 if x[i - 1] > x[i] else -360
                out_x[i + i_] = (x[i] - ref) % 360 + ref - cor
                out_y[i + i_] = y[i]
                out_x[i + i_ + 1] = nan
                out_y[i + i_ + 1] = nan
                out_x[i + i_ + 2] = (x[i - 1] - ref) % 360 + ref + cor
                out_y[i + i_ + 2] = y[i - 1]
                i_ += 3
            out_x[i + i_] = (x[i] - ref) % 360 + ref
            out_y[i + i_] = y[i]
        return out_x, out_y
    else:
        nb = x.shape[0]
        out = empty(nb, dtype=x.dtype)
        for i in range(nb):
            out[i] = (x[i] - ref) % 360 + ref
        return out, y

lon = array([28.1875, 28.206074, 28.233936, 28.271086, 28.308235, 28.317406, 28.344624, 28.371841, 28.40813, 28.413164])
lat = array([33.91166, 33.912666, 33.914177, 33.91619, 33.918205, 33.919373, 33.924557, 33.92974, 33.936653, 33.941406])
wrap_longitude(lon, lat, ref=-10, cut=True)
```

**Comment by limaolin1981611** [comment]
1 0.01857400000000098 0.01857400000000098
2 0.027861999999998943 0.027861999999998943
3 0.03714999999999691 0.03715000000000046
4 0.03714899999999943 0.03714899999999943
5 0.009171000000002039 0.009170999999998486
6 0.027217999999997744 0.027218000000001297
7 0.027217000000007374 0.02721700000000027
8 0.03628899999999646 0.036289000000000016
9 0.005033999999994876 0.005033999999998429
[]

Process finished with exit code 0

**Comment by limaolin1981611** [comment]
I install the eddy-tracker on macbook pro, the output figs of  pet_eddy_detection are correct。
But on windows, I reinstall the  eddy-tracker, the output figs of  pet_eddy_detection are wrong

**Comment by limaolin1981611** [comment]
I have installed the Anconda and eddy-tracker once again, the outputs are write.

**Comment by AntSimi** [comment]
For my information, how did you install on windows at first time?
