### ISSUE TITLE
 changed the date of eddy_detection, but the outputs were same. Is it wright?

### ISSUE THREAD

**Issue by limaolin1981611** [AntSimi/py-eddy-tracker#132]
1.I have changed the date of pet_eddy_detection.py, but the outputs were same. Is it wright?
2.I have download the nrt_global_allsat_phy_l4_20220206_20220206.nc, changed the date to 2022.02.06, but there were no outputs of pet_eddy_detection_gulf_stream.

**Comment by AntSimi** [comment]
# 1 I have changed the date of pet_eddy_detection.py, but the outputs were same. Is it right?
`Date` argument is used to label observation and not to select an index on input data in the following code :
```python
date = datetime(2016, 5, 15)
a, c = g.eddy_identification("adt", "u", "v", date, 0.002, shape_error=55)
```
Input selection must be do by user

# 2 I have download the nrt_global_allsat_phy_l4_20220206_20220206.nc, changed the date to 2022.02.06, but there were no outputs of pet_eddy_detection_gulf_stream
This question is too open/large for an answer, i didn't know this specific file and i don't know the meaning of no outputs.

**Comment by limaolin1981611** [comment]
what do you mean "Date argument is used to label observation"?

**Comment by AntSimi** [comment]
Date argument is used to set time for eddy observations in output file/object

**Comment by limaolin1981611** [comment]
thanks
