### ISSUE TITLE
 how can I get a part of data from the global file of sla?

### ISSUE THREAD

**Issue by limaolin1981611** [AntSimi/py-eddy-tracker#133]
I have download the globle file "nrt_global_allsat_phy_l4_20220206_20220206.nc", I can get the min and max value of sla used the code  "g.grid("adt").min()" and "g.grid("adt").max()".

So, how can I get a part of data from the file, for example, the latitude and longitude as follows:
lat_begin = 10
lat_end = 40
lon_begin = 100
lon_end = 180

**Comment by AntSimi** [comment]
Like in [this example](https://github.com/AntSimi/py-eddy-tracker/blob/master/examples/02_eddy_identification/pet_eddy_detection_gulf_stream.py#L44), you must give index.

**Comment by limaolin1981611** [comment]
I have tried this example, but I did not know to set the "indexs" and "margin"

**Comment by limaolin1981611** [comment]
I tried like this:

lat_begin = 29
lat_end = 44
lon_begin = 279
lon_end = 304

lat_begin_index = math.floor((lat_begin - (-90)) / 0.25)
lat_end_index = math.ceil((lat_end - (-90)) / 0.25)
lon_begin_index = math.floor(lon_begin / 0.25)
lon_end_index = math.ceil(lon_end / 0.25)
g = RegularGridDataset(
    data.get_demo_path(dt_file_name),
    "longitude",
    "latitude",
    # Manual area subset
    indexs=dict(
        longitude=slice(lon_begin_index, lon_end_index),
        latitude=slice(lat_begin_index, lat_end_index),
    ),# pet_eddy_detection not contain
)

**Comment by zhaotianzi** [comment]
![image](https://user-images.githubusercontent.com/33385974/155115961-55c231e4-0e18-4e5a-a38d-3962331c5e10.png)
Is this dataset available?

**Comment by AntSimi** [comment]
@zhaotianzi, py eddy tracker software is not a data provider, and i don't understand the link with the closed issue.

**Comment by zhaotianzi** [comment]
I'm using the new CMEMS data, and looking at the previous post, it doesn't seem to work, so I asked the previous question
old:nrt_global_allsat_phy_l4_20190223_20190226.nc
new:dataset-duacs-nrt-global-merged-allsat-phy-l4_1645522022743.nc


I'm sorry if it bothered you






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AntSimi/py-eddy-tracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月22日(星期二) 晚上11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AntSimi/py-eddy-tracker]  how can I get a part of data from the global file of sla? (Issue #133)





 
@zhaotianzi, py eddy tracker software is not a data provider, and i don't understand the link with the closed issue.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
