### ISSUE TITLE
use the new sla file to run pet_eddy_detection_gulf_stream.py

### ISSUE THREAD

**Issue by limaolin1981611** [AntSimi/py-eddy-tracker#137]
The longitude in file "nrt_global_allsat_phy_l4_20190223_20190226.nc" is from 0.125 to 359.875, but in file "nrt_global_allsat_phy_l4_20220201_20220207.nc" is from -179.875 to 179.875.

I used the "nrt_global_allsat_phy_l4_20220201_20220207.nc", changed the longitude in pet_eddy_detection_gulf_stream.py form "279~304" to "-101~-56", reset the "indexs" of "RegularGridDataset". But the longitudes of Cyclonic and Anticyclonic was  still from 0~360.

How Can I to fix it?

**Comment by AntSimi** [comment]
Eddy longitudes will be always stored from 0 to 360

**Comment by limaolin1981611** [comment]
ok

**Comment by limaolin1981611** [comment]
ok

**Comment by limaolin1981611** [comment]
So, If I want to use the new sla file, I need to change the vars the same as the old file?

**Comment by AntSimi** [comment]
Grid Longitudes must be increasing this is the only mandatory things. It could be between - 270 to 90 or 0 to 360 or....
