### ISSUE TITLE
External data -- Unregular grid

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#143]
Hello,

Here, https://py-eddy-tracker.readthedocs.io/en/stable/python_module/12_external_data/pet_SST_collocation.html
How do we re-grid or use the display using the Romsdataset on the Unregular grid:
https://github.com/AntSimi/py-eddy-tracker/issues/5

I am having the attribute error because the Romsdataset has no attribute 'display' or 'regird'

How to proceed with this?

**Comment by AntSimi** [comment]
Hi, this method are sadly  not implemented for unregular grid.
I am not a widely user of this type of grid, so i didn't take time to improve/write those methods.
This is something to improve and any contributions about it are welcome.

**Comment by Ashwita2619** [comment]
okay…
