### ISSUE TITLE
time series of external data on Unregular grid

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#144]
Hello,

Could you please assist me how could we go the time series of the external data
say, salinity or temperature which is on the unregular grid

**Comment by AntSimi** [comment]
Closer method to do that is [interp_grid](https://py-eddy-tracker.readthedocs.io/en/stable/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.interp_grid), but it's only for RegularGrid :(.
This method could be maybe implemented "efficently" on UnregularGrid if you are able to find "efficiently" eddy bounding box on  UnregularGrid coordinates to be able to test all pixel in this bounding box.

**Comment by Ashwita2619** [comment]
okay… thanks!
