### ISSUE TITLE
highlighting the end of the track

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#147]
Hi Antione,

There's an example to display the track:
https://py-eddy-tracker.readthedocs.io/en/stable/python_module/08_tracking_manipulation/pet_display_track.html#sphx-glr-python-module-08-tracking-manipulation-pet-display-track-py

but, is it also possible to highlight the end of the track by using the automatic method of the py-eddy-tracker?

Thanks,
Ashwita

**Comment by AntSimi** [comment]
Hi, you must select end of the track with [last obs method](https://py-eddy-tracker.readthedocs.io/en/stable/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.last_obs) and display object return.

**Comment by AntSimi** [comment]
To do that you need to do two display:
- one explain in previous message (to plot white dots with scatter method)
-  And to do red line use [plot method like in this example](https://py-eddy-tracker.readthedocs.io/en/stable/python_module/08_tracking_manipulation/pet_select_track_across_area.html#tracks-which-go-through-area)
