### ISSUE TITLE
Radius w.r.t. No. of eddies

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#148]
Hi Antione,

While computing the cdf or pdf of radius Vs number of eddies
I tried computing by fetching the speed radius -- a["speed_radius"] 
but it didn't worked…
Could you please assist me with this…

Thanks,
Ashwita

**Comment by AntSimi** [comment]
I don't know what cdf/pdf/wrt is?
Maybe you can share your tests to help us understand!

**Comment by Ashwita2619** [comment]
I was trying to plot (but it didn't worked) for
number of eddies on y-axis and radius on x-axis for cyclones and anticyclones
i.e., Number of eddies Vs radius
like -- https://py-eddy-tracker.readthedocs.io/en/stable/python_module/10_tracking_diagnostics/pet_propagation.html#sphx-glr-python-module-10-tracking-diagnostics-pet-propagation-py
but propagation in terms of radius…

**Comment by AntSimi** [comment]
Did you want to do this(figure) [https://py-eddy-tracker.readthedocs.io/en/stable/python_module/10_tracking_diagnostics/pet_histo.html#parameter-histogram]?

**Comment by Ashwita2619** [comment]
yes,
https://py-eddy-tracker.readthedocs.io/en/stable/python_module/10_tracking_diagnostics/pet_histo.html#parameter-histogram
this figure
but, on y-axis I want to have number of eddies

**Comment by AntSimi** [comment]
Set `density=False`, inplace of True, maybe you need to modify ylim also.
