### ISSUE TITLE
How to produce a zarr tracking dataset? 

### ISSUE THREAD

**Issue by yyj999999** [AntSimi/py-eddy-tracker#154]
Hello, I would like to ask how to modify the conf.yaml file so that the final data used for tracking is in zarr format, I use your yaml file and finally get nc format, I want to get the zarr file for later animation display .

**Comment by AntSimi** [comment]
Look at help of `EddyTracking` you will found options to do that.
`EddyTracking -h`

But if you use animation example in the documentation zarr or nc files will be ok
