### ISSUE TITLE
about polygon3 install

### ISSUE THREAD

**Issue by NTUBobWu** [AntSimi/py-eddy-tracker#158]
Hi! I have a question about pip install polygon3, I cannot install it by using pip install polygon3, I ran it, but some errors happing, so I want to ask you do you have any solution to this question.

**Comment by AntSimi** [comment]
I don't which platform did you use (unix , windows, ...) but maybe take a look at this [issue](https://github.com/AntSimi/py-eddy-tracker/issues/134#issuecomment-1036076136)

**Comment by NTUBobWu** [comment]
Thank you I think I find my problem, I need to download Microsoft C++ Build Tools.
