### ISSUE TITLE
Using multiple files or records 

### ISSUE THREAD

**Issue by ivicajan** [AntSimi/py-eddy-tracker#16]
Hi,
I would like to use eddy tracker on multiple time daily records (aviso or ROMS model). Tried to modify yaml file but stuck.
For start I downloaded daily values from mercator/copernicus subset of AVISO L4 (sla, adt and all other variables) for 1 month and would like to use the file as an input for eddy identification and tracking. I can do that for single date (as argument in eddy_identification).
Is there a way to specify argument for multiple dates or I have to use yaml file? Do you have some example with multiple time records?

Tried with modified example in ./share/ eddy_identification.yaml but no luck. It looks for FILE_PATERN key which should be generated using DATASET and FILES_MODEL with DATE_REGEXP?

(I even split those daily records into separate daily files and still not working)

Thanks in advance,
Ivica

**Comment by AntSimi** [comment]
Yaml file for identification is an old one it will be removed at next realease. If you grid is a regular one you could use eddyid, but it can process only one file by command and only is first time step if you several in one.
To process a time series create a bash or somethings like that. 
If your roms are unregular look at a previous closed issue.

**Comment by AntSimi** [comment]
Issue #5

**Comment by ivicajan** [comment]
Thanks a lot for swift reply!
Exactly what I needed for ROMS. 
I was thinking about bash script and looping with date variable but then I might endup with bunch of daily files for Cyclonic and Anticyclonic outputs. If I want to make analysis for example on life duration of individual eddies I need to aggregate those daily outputs and have some dimension and then take/find ID of that particular eddy that might change from file to file, or there is already tool/script available?

Cheers
Ivica

**Comment by ivicajan** [comment]
Regarding ROMS inputs, I have already rotated and at collapsed to rho coordinates both u_eastward and v_northward components (Rutgers ROMS have the option). So, according to your #5, all I should do is just to make that speed norm aware of units (change units)? I could do it quickly using NCO ncrename for velocity unit attributes and put them to "meter second^-1"?

Cheers
Ivica

**Comment by AntSimi** [comment]
> Thanks a lot for swift reply!
> Exactly what I needed for ROMS. 
> I was thinking about bash script and looping with date variable but then I might endup with bunch of daily files for Cyclonic and Anticyclonic outputs. If I want to make analysis for example on life duration of individual eddies I need to aggregate those daily outputs and have some dimension and then take/find ID of that particular eddy that might change from file to file, or there is already tool/script available?
> 
> Cheers
> Ivica
>  

Atlas is produced in two step, identification first and tracking after. For tracking you must used EddyTracking with a yaml file, and also choose method to track.
To subset atlas you could use eddysubsetter. You could also take a look at the gallery from documentation.

**Comment by AntSimi** [comment]
> Regarding ROMS inputs, I have already rotated and at collapsed to rho coordinates both u_eastward and v_northward components (Rutgers ROMS have the option). So, according to your #5, all I should do is just to make that speed norm aware of units (change units)? I could do it quickly using NCO ncrename for velocity unit attributes and put them to "meter second^-1"?
> 
> Cheers
> Ivica

I think you need just to have correct units. Speed norm was needed in previous case, because u/v used another dimensions than h.
