### ISSUE TITLE
How to subset eddy dataset on a specific area

### ISSUE THREAD

**Issue by hanyangliu1002** [AntSimi/py-eddy-tracker#161]
Dear maintainer,

  I have learned to download nc files from CMEMS and do global mesoscale eddy identification, but I need to look at the eddy  in my study area and show the number of eddy  in the area, how can I deal with it.

At present, the method I think of is to modify the nc file (remove the data in the non-research area), but I will only save it as a txt file. Can PET code read the txt file?

**Comment by hanyangliu1002** [comment]
In this example [Eddy detection on SLA and ADT], I use the data I downloaded from CMEMS, but the number of eddy is the number of global, not the number of study areas.

**Comment by AntSimi** [comment]
To subset eddy dataset you could use [this method](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.extract_with_area)

**Comment by hanyangliu1002** [comment]
Thank u
