### ISSUE TITLE
About methods of ensuring radius of eddies

### ISSUE THREAD

**Issue by NTUBobWu** [AntSimi/py-eddy-tracker#162]
Hi, I have a question about what method do you use to detect the edge of eddies. I find a method, but I do not know do you use the same method as it.
Appendix.B2 at
https://www.sciencedirect.com/science/article/pii/S0079661111000036?casa_token=L12_Q0TeLK4AAAAA:bo3j6NuOJolZ6inWAli5Mkror8mI0P1fZrAYNDSqtoCaXzLzqnDRhWBUf_qfiC77LNS_P3ZThLxA#s0155

**Comment by AntSimi** [comment]
Py eddy tracker methodology are described in this  [paper](https://doi.org/10.1175/JTECH-D-14-00019.1)

**Comment by NTUBobWu** [comment]
Thanks.

**Comment by NTUBobWu** [comment]
教授：
這是我目前的海報， 思路大致上與上次說的相同，
而解釋eddies速度那邊我會從中間的某個公式開始說，因為我怕從頭開始放上去會放不下，如果有教授或其他人問的話，我會額外解釋給他們聽。

Antoine Delepoulle ***@***.***> 於 2022年8月26日 週五 凌晨12:26寫道：

**Comment by NTUBobWu** [comment]
Oh, sorry. I send to wrong person.

Antoine Delepoulle ***@***.***>於 2022年8月26日 週五，下午3:11寫道：
