### ISSUE TITLE
Death frequency over the boxed region

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#164]
Hi Antione,

I was trying to obtain the death frequency for anticyclones (or cyclones) which falls in the boxed region

Here: https://py-eddy-tracker.readthedocs.io/en/stable/python_module/08_tracking_manipulation/pet_select_track_across_area.html#sphx-glr-python-module-08-tracking-manipulation-pet-select-track-across-area-py
we could see the trajectories inside the box.

Is it also possible to generate a map like this:
https://py-eddy-tracker.readthedocs.io/en/stable/python_module/10_tracking_diagnostics/pet_birth_and_death.html#sphx-glr-python-module-10-tracking-diagnostics-pet-birth-and-death-py
over a boxed region?

**Comment by AntSimi** [comment]
I think you just need to change bin parameters

**Comment by Ashwita2619** [comment]
We could change the binned box.
But, I was wondering to have the map (for birth or death frequencies) of the trajectories which are only crossing the box and ignoring the tracks which lies outside of the box…

**Comment by AntSimi** [comment]
Do a subset of your atlas, here `c` is atlas
```python
x0, x1, y0, y1 = 3, 4, 37, 38
area = dict(llcrnrlon=x0, llcrnrlat=y0, urcrnrlon=x1, urcrnrlat=y1)
c_subset = c.extract_with_area(area, full_path=True)
```
You could play with `extract_with_area` options to select trajectories that you want

Before to compute binning
```python
c_subset.first_obs().grid_count(bins, intern=True)
```

**Comment by Ashwita2619** [comment]
thank you :)
