### ISSUE TITLE
Number of interaction

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#169]
Hi Antione,

How could we quantify the interaction of a particular trajectory with its neighbouring anticyclones and cyclones?
Or quantifying the interactions in general -- the interaction of an anticyclone with its neighbouring cyclones?

**Comment by AntSimi** [comment]
What did you mean by quantify?
I never try to study interaction between Cyclone and Anticyclone

**Comment by Ashwita2619** [comment]
by quantify -- I meant to have a count of the interactions

**Comment by AntSimi** [comment]
I didn't do any work to observe interactions between network.
