### ISSUE TITLE
wrong labeling in example/02 and pet_sla_and_adt.py

### ISSUE THREAD

**Issue by ivicajan** [AntSimi/py-eddy-tracker#17]
It's just minor correction to be consistent;
when you plot c and a for _adt  and/or _sla kwargs call  is mixed up:
 a_adt.display(ax, **kwargs_a_adt), c_adt.display(ax, **kwargs_a_sla) 
think it should be:
a_adt.display(ax, **kwargs_a_adt), c_adt.display(ax, **kwargs_c_adt)

and so on in the rest of file...

Thanks for sharing really cool stuff!

Cheers
Ivica

**Comment by AntSimi** [comment]
Well done, I will correct it

**Comment by ivicajan** [comment]
It is not issue but more question regarding usage;
I have created individual netCDF files for each day (Cyclonic and
Anticyclonic) and would like to run tracking. As I can see you are
using zarr (is this mimic of aggregation of multiple netCDF files?),
is this compulsory or I can get away with multiple netCDF files in one
folder? Do you have example how to make the zarr file from daily
netCDF "A" and "C" files?

Thanks in advance,
Ivica

**Comment by ivicajan** [comment]
I managed to get it over with yaml file

**Comment by Kris-wu-glut** [comment]
> 这不是问题，而是有关用法的更多问题；我每天都创建了单独的netCDF文件（气旋和反气旋），并希望运行跟踪。如我所见，您正在使用zarr（这是多个netCDF文件的聚合模仿吗？），这是强制性的，还是我可以摆脱一个文件夹中的多个netCDF文件的困扰？您是否有示例如何从每日netCDF“ A”和“ C”文件制作zarr文件？在此先感谢，Ivica
> […](#)
> 在2020年7月23日，星期四，00：06，AntSimi ***@***.***>写道：做得好，我将更正它-您收到此消息是因为您编写了线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

I have the same problem, how did you solve it？

**Comment by AntSimi** [comment]
Sorry I don't understand Chinese characters. I solve wrong labeling in a recent commit, I just swap kwargs to have correct one

**Comment by Kris-wu-glut** [comment]
@ivicajan   I also have individual netCDF files for each day (Cyclonic and
Anticyclonic) .I wonder how you implement eddy tracking？

**Comment by AntSimi** [comment]
> @ivicajan I also have individual netCDF files for each day (Cyclonic and
> Anticyclonic) .I wonder how you implement eddy tracking？

look at answer in #19
