### ISSUE TITLE
Merging and splitting over a boxed region

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#171]
Hi Antione,

I wanted to see the merging and splitting in the boxed region
I was implementing the same logic as in #164  (but, it doesn't work for merging)
and has a type error:
TypeError: extract_with_mask() got an unexpected keyword argument 'full_path'

Could you please assist me as to how this can be sorted?

**Comment by AntSimi** [comment]
`full_path` option for `NetworkObservations.extract_with_mask` [are not implemented](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.network.NetworkObservations.html#py_eddy_tracker.observations.network.NetworkObservations.extract_with_mask)
