### ISSUE TITLE
Time Series Plots

### ISSUE THREAD

**Issue by abhijithpkurian** [AntSimi/py-eddy-tracker#18]
How can the time series analysis be done. It would be great if a sample can be provided as the Anticyclonic.nc nor Cyclonic.nc gives an idea about the time/date.

**Comment by AntSimi** [comment]
You could look at this gallery for example https://py-eddy-tracker.readthedocs.io/en/latest/python_module/index.html#tracking-diagnostics it use those samples https://github.com/AntSimi/py-eddy-tracker-sample
