### ISSUE TITLE
Tracking & Eddyes_ids

### ISSUE THREAD

**Issue by Manuel-Fundora** [AntSimi/py-eddy-tracker#180]
Run the trackers
How can i get the eddys ids for my area? i tried used the variable "track"
```python
# Track animation with standard matplotlib
========================================

Run in a terminal this script, which allow to watch eddy evolution.

You could use also *EddyAnim* script to display/save animation.

"""
import re
from matplotlib.animation import FuncAnimation
from numpy import arange
import py_eddy_tracker_sample
from py_eddy_tracker.appli.gui import Anim
from py_eddy_tracker.observations.tracking import TrackEddiesObservations

# sphinx_gallery_thumbnail_path = '_static/no_image.png'


# %%
class VideoAnimation(FuncAnimation):
    def _repr_html_(self, *args, **kwargs):
        """To get video in html and have a player"""
        content = self.to_html5_video()
        return re.sub(
            r'width="[0-9]*"\sheight="[0-9]*"', 'width="100%" height="100%"', content
        )

    def save(self, *args, **kwargs):
        if args[0].endswith("gif"):
            # In this case gif is used to create thumbnail which is not used but consume same time than video
            # So we create an empty file, to save time
            with open(args[0], "w") as _:
                pass
            return
        return super().save(*args, **kwargs)


# %%
# Load experimental atlas, and we select one eddy
filename_1 = "Anticyclonic_PTFM.nc"
a = TrackEddiesObservations.load_file(
    py_eddy_tracker_sample.get_demo_path(
        f"C:/Users/LENOVO/Downloads/AVISO EDDIES/{filename_1}"
    )
)
eddy = a.extract_ids([1387])

# %%
# Run animation
a = Anim(eddy, intern=True, figsize=(8, 3.5), cmap="magma_r", nb_step=5, dpi=50)
#a.txt.set_position((17, 34.6))
#a.ax.set_xlim(16.5, 23)
#a.ax.set_ylim(34.5, 37)

# arguments to get full animation
kwargs = dict(frames=arange(*a.period)[300:800], interval=90)

ani = VideoAnimation(a.fig, a.func_animation, **kwargs)
#
#
```

https://user-images.githubusercontent.com/116701311/204865113-7ff493d7-40f8-4180-9a57-db9ca1d7c3ec.mp4

![Actual_Output](https://user-images.githubusercontent.com/116701311/204865114-f16e1db1-882b-48e7-ac88-dbccadb4a988.png)
[Anticyclonic_PTFM.zip](https://github.com/AntSimi/py-eddy-tracker/files/10125631/Anticyclonic_PTFM.zip)

**Comment by Manuel-Fundora** [comment]
Hi, I'm trying to track a particular eddy for my study region, how can I get the ids of those eddies involved. On the other hand, in the scripts corresponding to the tracking (pet_one_track, pet_track_anim, pet_track_anim_matplotlib_animation) when I use my database and change the id it does not make the video. Could you help me. Thank you very much, I am attaching my cropped area from A.VISO atlas.

**Comment by AntSimi** [comment]
If you know already which eddy that you want to display take a look to track field to get ID
If you don't know you could do a global animation with
```bash
EddyAnim --all MY_FILE
```

**Comment by AntSimi** [comment]
use option `--infinity_loop` to see other option take a look at `EddyAnim -h`
If you want help on your mp4 error , share traceback

**Comment by Manuel-Fundora** [comment]
In the case of the console, it makes the animation for me but it doesn't save it, I share the error. For the script it is different, it runs without problems but it does not generate video, just an image of the area with nothing inside.
![Figure 2022-12-05 112417](https://user-images.githubusercontent.com/116701311/205713739-19969013-4578-4166-9c89-e61c302bb911.png)
![Captura](https://user-images.githubusercontent.com/116701311/205713742-e6b04785-f665-405a-940b-75beca518218.PNG)

**Comment by Manuel-Fundora** [comment]
ok, thanks

**Comment by Manuel-Fundora** [comment]
hello, in my case study I started following the eddy 599333, which is located in the Mexican Pacific (15-25 N and 105-115 W). For this eddy the track_animation shows me how they only have 136 days of life, even in the animation their radius seems to decrease, however according to altimetry images and geostrophic speeds from Copernicus that eddy persisted for a few more weeks. Could it be an error in the algorithm or in the AVISO+ database?

**Comment by AntSimi** [comment]
There are several dataset in AVISO , which one did you take?

**Comment by AntSimi** [comment]
There are some parameters to manage tracking, one of them is overlap criterion describe in [handbook](https://www.aviso.altimetry.fr/fileadmin/documents/data/tools/hdbk_eddytrajectory_META3.1exp_DT.pdf) section 3.2.4, two consecutiv eddies must have an overlap ratio > 5 %.

We could see in the following video that eddies continue under a new ID ...
```python
from py_eddy_tracker.observations.tracking import TrackEddiesObservations
from matplotlib import pyplot as plt
import pylook
from py_eddy_tracker.appli.gui import Anim
from py_eddy_tracker.misc import VideoAnimation
import numpy as np
from py_eddy_tracker.poly import vertice_overlap

# eds = TrackEddiesObservations.load_file(f'/data/OCTANT_NG/eddies/tracking/20220323_CMEMS_DT2021_META3.2/Anticyclonic.nc').extract_with_period((23500, 23850), full_path=True).extract_with_area(dict(llcrnrlon=-120, urcrnrlon=-100, llcrnrlat=15, urcrnrlat=30), full_path=True)
# eds.write_file(filename='Anticyclonic_issue_180.nc')

a_issue = TrackEddiesObservations.load_file(f'Anticyclonic_issue_180.nc')
ed_599333 = a_issue.extract_ids([599333])
ed_609664 = a_issue.extract_ids([609664])

fig = plt.figure(figsize=(20,10))
ax = fig.add_axes([0.05,0.05,.9,.9], projection='plat_carre')
ax.set_xlim(235,260), ax.set_ylim(15,26)
ax.update_env()
ax.grid()
a = Anim(a_issue, intern=True, figure=fig, position=ax, cmap="magma_r", nb_step=5, dpi=90)
a.txt = ax.text(256,24.1, '')
kwargs = dict(frames=np.arange(23619.0-10, 23754.0 + 30), interval=200)
ani = VideoAnimation(a.fig, a.func_animation, **kwargs)
ani.save('anim599333.mp4')
```
https://user-images.githubusercontent.com/36040805/208125673-dcc01f4f-56e1-4144-83ca-24498c532f67.mp4

If we check overlap between first obs of 609664 and last obs of 599333, we have an overlap under 5% :(, It something knew, and we try to bring a solution to this problem in the further atlas.
```python
vertice_overlap(ed_599333.contour_lon_e[-1:], ed_599333.contour_lat_e[-1:], ed_609664.contour_lon_e[:1], ed_609664.contour_lat_e[:1])
```
```
array([4.57560508])
```

**Comment by Manuel-Fundora** [comment]
Thank you very much, I find the py_eddy_tracker tool very useful. I don't know much about programming and at times it's a bit difficult for me to interact with the code. Is there a way to extract the EKE values for a specific eddy? I refer to the fact of being able to analyze its temporal variation during the lifetime of the eddy. Do I need to open a new issue for this? Thanks for being outstanding.
