### ISSUE TITLE
how to subset on my area

### ISSUE THREAD

**Issue by MetoLiang** [AntSimi/py-eddy-tracker#181]
I already downloaded the data for the eddies from AVISO (META3.2_DT_allsat_Cyclonic_long_19930101_20220209.nc) for both cyclonic and anticyclonic.I want to subset on my area(lat = 8 N to 32 N,lon = 103 E to 132 E,time = '2015-09=30' ),What should I do with the data.

**Comment by AntSimi** [comment]
Read this https://github.com/AntSimi/py-eddy-tracker/issues/173#issuecomment-1310319038

**Comment by MetoLiang** [comment]
Thank you very much for your help and time
