### ISSUE TITLE
Eddies lifetime histogram in the example.  Why there is negative power of 10?

### ISSUE THREAD

**Issue by AntSimi** [AntSimi/py-eddy-tracker#190]
I would like to ask about the livetime Histogram of the eddy in the example of the pyeddytracker document. Is his vertical axis the number of eddy? Why is there a negative power of 10?
![擷取](https://user-images.githubusercontent.com/104262092/218693745-606ddaec-025c-431e-b19c-d5b1698097ef.JPG)

_Originally posted by @hanyangliu1002 in https://github.com/AntSimi/py-eddy-tracker/issues/21#issuecomment-1429397275_

**Comment by AntSimi** [comment]
Number could be inferior of 1, because we divide by the number of year. But value are still greater than 0

**Comment by hanyangliu1002** [comment]
Thanks !
