### ISSUE TITLE
About tracking eddy files

### ISSUE THREAD

**Issue by hanyangliu1002** [AntSimi/py-eddy-tracker#191]
Dear Dr.AntSimi,

 1. I can output the one day cyclonic/ Anticyclonic .nc file, but how to output for more long time, such as month, year.... (e.g. example([Track in python](https://py-eddy-tracker.readthedocs.io/en/stable/python_module/08_tracking_manipulation/pet_run_a_tracking.html#sphx-glr-python-module-08-tracking-manipulation-pet-run-a-tracking-py)))
 2. I download the data ([MESOSCALE EDDY TRAJECTORY ATLAS PRODUCT](https://data.aviso.altimetry.fr/aviso-gateway/data/META3.1exp_DT/META3.1exp_DT_allsat/ )) from AVISO, can we use this data to track and analyze eddies(e.g. plot the Lifetime Histogarm or tracking eddies).
 the data period is 1993/01/01 to 2020/03/07, Can we extract the time we want to study from this data
3. When I use the example ([Lifetime Histogram](https://py-eddy-tracker.readthedocs.io/en/stable/python_module/10_tracking_diagnostics/pet_lifetime.html#sphx-glr-python-module-10-tracking-diagnostics-pet-lifetime-py)) ，show the flowing error :

File was created with py-eddy-tracker version 'None' but software version is '3.6'
File was created with py-eddy-tracker version 'None' but software version is '3.6'
x:\MasterStudent_HY\PET-Method\Lifetime\pet_lifetime.py:57: RuntimeWarning: invalid value encountered in true_divide
  ax_ratio_cum.plot(x, cum_c / cum_a)
x:\MasterStudent_HY\PET-Method\Lifetime\pet_lifetime.py:58: RuntimeWarning: divide by zero encountered in true_divide
  ax_ratio.plot(x, nb_c / nb_a)
x:\MasterStudent_HY\PET-Method\Lifetime\pet_lifetime.py:58: RuntimeWarning: invalid value encountered in true_divide 
  ax_ratio.plot(x, nb_c / nb_a)

what should I do ?

Many thanks for your help!!!

H.Y.

**Comment by AntSimi** [comment]
This is not error but warning which are also visible on example

**Comment by AntSimi** [comment]
To reduce memory comsumption you could select field loaded, or do a subset of atlas with EddySubSetter on various criterions.

**Comment by hanyangliu1002** [comment]
Dear Dr.AntSimi,

Thank you for your answer.
How do I select field loaded and What instruction can use ?

Can we use this indexs=dict(variable=silce(,))

**Comment by AntSimi** [comment]
You could look at the documentation [here](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.load_file)
