### ISSUE TITLE
Could you tell me how to solve this

### ISSUE THREAD

**Issue by zhouxingyulijingru** [AntSimi/py-eddy-tracker#192]
![image](https://user-images.githubusercontent.com/127758645/224984280-23c72ee6-23d8-4197-80c2-ed07a3bebfec.png)

**Comment by AntSimi** [comment]
It's look like a problem with scipy installation. Which are independant of PyEddyTracker.

**Comment by zhouxingyulijingru** [comment]
Thank you. I have one more question.
How do we solve this
We assume pixel position of grid is centered for C:\Users\zxy24\AppData\Roaming\Python\Python39\site-packages\py_eddy_tracker\data\dt_med_allsat_phy_l4_20160515_20190101.nc

**Comment by zhouxingyulijingru** [comment]
Thank you
