### ISSUE TITLE
[Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by zhouxingyulijingru** [AntSimi/py-eddy-tracker#193]
Can you help me?When I run pet_statistics_on_identification
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /AntSimi/py-eddy-tracker-sample-id/master/eddies_med_adt_allsat_dt2018/Anticyclonic_2010_2011_2012.tar.xz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025A1F497B50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by AntSimi** [comment]
This example need download data.
