### ISSUE TITLE
How do we fix this

### ISSUE THREAD

**Issue by zhouxingyulijingru** [AntSimi/py-eddy-tracker#194]
![image](https://user-images.githubusercontent.com/127758645/226103076-0d9b131e-aaee-4d99-8e9c-9212f4c1c34d.png)

**Comment by iamzdy** [comment]
I have also met such problems. Have you solved it?

**Comment by AntSimi** [comment]
Which version of python/numba/numpy did you use?

**Comment by AntSimi** [comment]
This problem persist with last master version available on github? With python 3.10?
