### ISSUE TITLE
Contours of detected Eddies are not closed

### ISSUE THREAD

**Issue by iamzdy** [AntSimi/py-eddy-tracker#197]
Hello, all.

The output from official codes shows strange features. It seems that the contours of detected eddies are not closed and are connected between western and eastern boundaries. I looked up previous issues and found similar problems which are solved by using python 3.6. I am really curious about why this happened.

![image](https://user-images.githubusercontent.com/65277875/230312185-382543fd-3453-4cbf-a02a-8edd1c54517f.png)

**Comment by AntSimi** [comment]
Which python version did you use?

**Comment by AntSimi** [comment]
Which python version did you use?
