### ISSUE TITLE
When multiple dates of altimetry datas are combined in a single file 

### ISSUE THREAD

**Issue by acapet** [AntSimi/py-eddy-tracker#20]
Hi AntSimi, 

We have the case were altimetry data are gathered in a single netcdf file, including a "time" dimension for each particular date. 
Is there a way to load a particular date within a file with `RegularGridDataset` ? 
Or should we rather split our netcdf file in singular files for each date ? 

Thanks !

**Comment by AntSimi** [comment]
Hi,

To specify a non-coordinates index you could read this docstring [GridDataset](https://py-eddy-tracker.readthedocs.io/en/stable/autodoc/grid.html#py_eddy_tracker.dataset.grid.GridDataset), you need to use indexs option.
If you choose this solution you will need to apply manually all operation describe [here](https://py-eddy-tracker.readthedocs.io/en/stable/python_module/02_eddy_identification/pet_eddy_detection.html#sphx-glr-python-module-02-eddy-identification-pet-eddy-detection-py) : filtering(if wanted), identification, storage

If you split in several files you could also use directly  [EddyId](https://py-eddy-tracker.readthedocs.io/en/stable/grid_identification.html#shell-bash-command).

Antoine

**Comment by acapet** [comment]
Thanks, 

To test this I've build some new files. So i have one one hand, individual daily files, and on the other hand a single file concatenated from the others using NCO tools, along a (now) record dimension "time". 

While I was loading individual files as such before : 
`
g = RegularGridDataset("../l4_cmems/dt_blacksea_allsat_phy_l4_"+dat1+"_20200801.nc", lon_name, lat_name)
`

I now attempted to load a slice from the concatenated file as follows : 

`g = GridDataset(filename="../l4_cmems/dt_blacksea_allsat_phy_l4_201404_20200801_tr.nc",
                x_name=lon_name,
                y_name=lat_name, 
                indexs={'time':23467})`

which results with the error : 

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyEddyTracker-3.2.0+0.g775b28f.dirty-py3.8.egg/py_eddy_tracker/dataset/grid.py in __init__(self, filename, x_name, y_name, centered, indexs, unset)
    328         if not unset:
    329             self.load_general_features()
--> 330             self.load()
    331 
    332     @property

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyEddyTracker-3.2.0+0.g775b28f.dirty-py3.8.egg/py_eddy_tracker/dataset/grid.py in load(self)
    415 
    416         self.setup_coordinates()
--> 417         self.init_pos_interpolator()
    418 
    419     def setup_coordinates(self):

AttributeError: 'GridDataset' object has no attribute 'init_pos_interpolator'

Is there a missing update of the 'GridDataset' function, or am I not setting the indexs argument correctly ? 

Thanks !

**Comment by AntSimi** [comment]
Sorry, i was not explicit you must still use RegularGridDataset, just i give you help of GridDataset because RegularGridDataset inherit from: [doc of RegularGridDataset](https://py-eddy-tracker.readthedocs.io/en/stable/autodoc/grid.html#py_eddy_tracker.dataset.grid.RegularGridDataset)

**Comment by acapet** [comment]
Thanks !
