### ISSUE TITLE
Erros about EddyTracking use hycom data(3hours)

### ISSUE THREAD

**Issue by limaolin1981611** [AntSimi/py-eddy-tracker#200]
I have detected the eddies using the hycom data(3hours), the outputs as flollows:
West_Pacific_Anticyclonic_2023042112.nc 
West_Pacific_Anticyclonic_2023042115.nc
West_Pacific_Anticyclonic_2023042118.nc
West_Pacific_Anticyclonic_2023042121.nc
West_Pacific_Anticyclonic_2023042200.nc
West_Pacific_Anticyclonic_2023042203.nc
West_Pacific_Anticyclonic_2023042206.nc
West_Pacific_Anticyclonic_2023042209.nc
......
West_Pacific_Anticyclonic_2023042900.nc

then I run "EddyTracking my_conf_AntiCyclonic.yaml -v DEBUG", but erros as flollows:
Several timesteps in grid dataset[    3    53   3479].

**Comment by limaolin1981611** [comment]
[West_Pacific_Anticyclonic_2023042112.zip](https://github.com/AntSimi/py-eddy-tracker/files/11337805/West_Pacific_Anticyclonic_2023042112.zip)
[my_conf_AntiCyclonic.zip](https://github.com/AntSimi/py-eddy-tracker/files/11337808/my_conf_AntiCyclonic.zip)

**Comment by AntSimi** [comment]
Short answer: i didn't write a flexible date reader from filename.
[Filename must use on of this pattern](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/__init__.py#L110 )
Try to rename your file like this:
```
West_Pacific_Anticyclonic_2023042112.nc -> West_Pacific_Anticyclonic_20230421T120000.nc or West_Pacific_Anticyclonic_20230421120000.nc
```
