### ISSUE TITLE
Straight lines in tracking plot

### ISSUE THREAD

**Issue by marimpacheco** [AntSimi/py-eddy-tracker#205]
Hii, I am getting straight lines on my plot after tracking. At first, I tracked only three timesteps and there were no lines, but when I added more timesteps to the tracking, those lines were added. They also appear when I do a longer tracking (without adding new files to the correspondance).

and two quick questions:
1- how can I know which are the pixel limits for detection (and how to redefine them)?
2- what does the parameter 'factor' do in "g.high_filter()"?
Thanks a lot!

```python
run = 0 # 1 for CO2-forced; 0 for control
eddy_type = 'Cyclonic'

file_objects = sorted(glob(datapath + '{}/'.format('V03_1PctTo4X' if run == 1 else 'Control-1860_V03') +
                   'detection/{}_*.nc'.format(eddy_type)))
c_c = Correspondances(datasets=file_objects[0:50], class_method=AreaTracker)
c_c.track()
c_c.prepare_merging()
eddies_area_tracker_c = c_c.merge(raw_data=False)

eddies_area_tracker_c.virtual[:] = eddies_area_tracker_c.time == 0

eddies_area_tracker_c.filled_by_interpolation(eddies_area_tracker_c.virtual == 1)

eddies_area_tracker_c.extract_with_length((2,-1))
fig = plt.figure(figsize=(10, 5))
ax = fig.add_axes([0.05, 0.03, 0.90, 0.94])
eddies_area_tracker_c.plot(ax=ax)
```

![Screenshot 2023-06-23 at 10 35 17](https://github.com/AntSimi/py-eddy-tracker/assets/63513909/901097cd-5fe6-4cd5-9e34-7f3e80cf0847)

```
# Name                    Version                   Build  Channel
python                    3.10.9               h7a1cb2a_0  
pyeddytracker             3.6.1+3.g7fc19df          pypi_0    pypi
```

**Comment by AntSimi** [comment]
Try to use [`ref` option](https://py-eddy-tracker.readthedocs.io/en/stable/_autosummary/py_eddy_tracker.observations.network.NetworkObservations.html#py_eddy_tracker.observations.network.NetworkObservations.plot) maybe set to 0, to avoid path crossing bounds:

**Comment by AntSimi** [comment]
You could change [`pixel_limit` in eddy_identification option](https://py-eddy-tracker.readthedocs.io/en/stable/_autosummary/py_eddy_tracker.dataset.grid.GridDataset.html#py_eddy_tracker.dataset.grid.GridDataset.eddy_identification), default value could be [see here](https://py-eddy-tracker.readthedocs.io/en/stable/_modules/py_eddy_tracker/dataset/grid.html#GridDataset.eddy_identification)

**Comment by AntSimi** [comment]
`factor` option is a dirty parameter to compute regular grid step before filtering, high_filter method in UnregularGrid is far away to be perfect.

**Comment by marimpacheco** [comment]
Thanks for answering very fast!
But what would be the difference if I use, for example, g.high_filter('SSH', w_cut= 700, factor=0.8) and one without factor?

Using ref=0 in eddies_area_tracker_c.plot() did not change anything, I continue with the lines.

**Comment by AntSimi** [comment]
After a quick [check maybe apply `normalize_longitude` before filled_by_interpolation](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/appli/eddies.py#L366C20-L366C39)

**Comment by AntSimi** [comment]
I wrote filter for Unregular grid long time ago. [But default value of factor is 8](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/dataset/grid.py#L1147), to sample signal 8 times by cycle, but feel free to play with this parameter or use own filter to remove large scale.

**Comment by marimpacheco** [comment]
Now it works, thank you very much!
