### ISSUE TITLE
detection and tracking eddy  from sea level anomaly from  satellite altimetry data

### ISSUE THREAD

**Issue by hafez-ahmad** [AntSimi/py-eddy-tracker#21]
thank you for making a wonderfull python package. I am trying to detect and track eddies from satellite altimetry data.
would you add an example of how to detect and track from gridded  (0.25 X 0.25 degree resolution) data on sea surface height, Sea level anomaly. 
satellite data: https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-sea-level-global?tab=overview

thank you

**Comment by AntSimi** [comment]
Did you read [this topic about altimetry grid identification](https://py-eddy-tracker.readthedocs.io/en/latest/grid_identification.html) ?
For tracking you could also read [this](https://py-eddy-tracker.readthedocs.io/en/latest/run_tracking.html).
If this informations don't allow you to produce eddy dataset, please give me more information about your problem.

Antoine

**Comment by hafez-ahmad** [comment]
thank you for your @AntSimi  response and I am now able to run the detect part.
I have a few questions 
1. how can I generate 'Anticyclonic_20190223.nc' ,'cyclonic_20190223.nc' and 'Cyclonic.zarr' files ?
2. how to measure eddies lifetime, velocity from daily dataset?
3. can I make detect longer life eddies?

I appreciate your wonderful python package @py-eddy-tracker and thank you again

**Comment by AntSimi** [comment]
> thank you for your @AntSimi response and I am now able to run the detect part.
> I have a few questions
> 
> 1. how can I generate 'Anticyclonic_20190223.nc' ,'cyclonic_20190223.nc' and 'Cyclonic.zarr' files , antiCyclonic.zarr'?
>    previously I created a and c observations, is any way to convert it into zarr file ? or concatenate multiple a /c observations?

Like you said in introduction i assume you are able to manage detection, just maybe be carefull with filter your area is tiny and high order of filter is very sensitive, (i guess you use **EddyId** tools to detect, maybe in your case use *–cut_wavelength* option and set to 0 to remove filtering step )
So after produce a whole period of identification(you told about 16 years), you could [run tracking](https://py-eddy-tracker.readthedocs.io/en/latest/run_tracking.html#default-method) it will produce eddy atlas in netcdf or zarr (use option for zarr).

> 2. how to measure eddies lifetime, velocity from daily dataset?

After create atlas you will able to follow [tracking example](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/index.html#tracking-manipulation), you must found information about each tracked path in atlas file

> 3. can I make detect longer life eddies?
>    I can make a, c for daily,I like to calculate for a year together

Linked to 1. and 2.

> 4. how can I generate a weekly plot like this from netcdf file  [ lifetimes of 4 weeks or longer over the 16-year data record; eddies with lifetimes shorter than 4 weeks were discarded.] I guess , I need antiCyclonic.zarr' files and Cyclonic.zarr' files
>    [I am able to generate this plot from you file and I cannot from my files ]
>    ![image](https://user-images.githubusercontent.com/20365917/94147614-5357c800-fe97-11ea-98b5-247a6d620f73.png)
>    I have attached three of NC files [2010-01-01,2010-01_02,2010_01_3] [https://www.dropbox.com/sh/gle4f758gy6yiiq/AACoMeXZ1uBelyQ6bqW7OfIaa?dl=0]

Linked to 1. and 2.

**Comment by hafez-ahmad** [comment]
@AntSimi thank you so much. you are super helpful. I really appreciate your time and assistance.

**Comment by hafez-ahmad** [comment]
@AntSimi 
**1.  I am trying to save a into ncfile/ zarr file, I am getting error 
`a.to_netcdf('Anticyclonic.nc')`**
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-10-ac586b9fe156> in <module>
----> 1 a.to_netcdf('Anticyclonic.nc')
      2 

~\personal\python_projects\sea_level_gridded\scripts\py-eddy-tracker-master\src\py_eddy_tracker\observations\observation.py in to_netcdf(self, handler, **kwargs)
   1067         eddy_size = len(self)
   1068         logger.debug('Create Dimensions "obs" : %d', eddy_size)
-> 1069         self.netcdf_create_dimensions(handler, "obs", eddy_size)
   1070         handler.track_extra_variables = ",".join(self.track_extra_variables)
   1071         if self.track_array_variables != 0:

~\personal\python_projects\sea_level_gridded\scripts\py-eddy-tracker-master\src\py_eddy_tracker\observations\observation.py in netcdf_create_dimensions(handler, dim, nb)
   1055     @staticmethod
   1056     def netcdf_create_dimensions(handler, dim, nb):
-> 1057         if dim not in handler.dimensions:
   1058             handler.createDimension(dim, nb)
   1059         else:

AttributeError: 'str' object has no attribute 'dimensions'



#Load an experimental med atlas over a period of 26 years (1993-2019)
```
a = TrackEddiesObservations.load_file(
    py_eddy_tracker_sample.get_path("eddies_med_adt_allsat_dt2018/Anticyclonic.zarr")
)
c = TrackEddiesObservations.load_file(
    py_eddy_tracker_sample.get_path("eddies_med_adt_allsat_dt2018/Cyclonic.zarr")
)
```

```
**how to run "conf.yaml"?** 
Example of conf.yaml

PATHS:
  # Files produces with EddyIdentification
  FILES_PATTERN: C:/Users/hafez/personal/python_projects/sea_level_gridded/scripts/py-eddy-tracker-master/share/Anticyclonic_*.nc
  # Path for saving of outputs
  SAVE_DIR: 'C:/Users/hafez/personal/python_projects/sea_level_gridded/scripts/py-eddy-tracker-master/share/'

# Minimum number of observations to store eddy
TRACK_DURATION_MIN: 10
VIRTUAL_LENGTH_MAX: 3




EddyTracking conf.yaml -v DEBUG
2. I tried to run in windows cmd , 'EddyTracking' is not recognized as an internal or external command,
operable program or batch file' . do I need to run it in jupyter notebook ?
 
```
Anticyclonic.zarr and Cyclonic.zarr

**Comment by AntSimi** [comment]
1.

You use [methods](https://py-eddy-tracker.readthedocs.io/en/latest/autodoc/observations.html#py_eddy_tracker.observations.observation.EddiesObservations.to_netcdf) which need handler and not a string.
If you want just specify name use instead [write_file](https://py-eddy-tracker.readthedocs.io/en/latest/autodoc/observations.html#py_eddy_tracker.observations.observation.EddiesObservations.write_file)

2.

A personal advice, don't mix module folder and your data (i think it's not a problem for py_eddy_tracker)
I didn't work on windows, so i am not aware how to get install command.
For your identification file you must have name like ....._%Y%m%d.nc => ...._20001020.nc for a file which will contain eddies of 20/10/2000.

You have already an example of tracking in gallery [how to run a tracking with module](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/08_tracking_manipulation/pet_run_a_tracking.html#track-in-python)
It used [Correspondances class](https://py-eddy-tracker.readthedocs.io/en/latest/autodoc/tracking.html#py_eddy_tracker.tracking.Correspondances)

**Comment by hafez-ahmad** [comment]
@AntSimi  thank you gain for response and guidance 
I read daily sla file and then use for loop for merging in to single one  then I save it as zarr file 
may be i am doing wrong thing 
```
c00=cc1[0]

for i in range(1,3717):
    c00=c00.merge(cc1[i])

a00=aa1[0]
for i in range(1,3717):
    a00=a00.merge(aa1[i])

```

#**c00= 65238 observations and a00=62180 observations**
# save file into zarr file 
`c00.write_file(path='C:/Users/hafez/personal/python_projects/gui/eddi/',filename="cc_full.zarr",zarr_flag=False)`
`a00.write_file(path='C:/Users/hafez/personal/python_projects/gui/eddi/',filename="ac_full.zarr",zarr_flag=False)`
# loading the  experimental med atlas over a period of 10  years
```
a = TrackEddiesObservations.load_file("C:/Users/hafez/personal/python_projects/gui/eddi/ac_full.zarr")
c = TrackEddiesObservations.load_file("C:/Users/hafez/personal/python_projects/gui/eddi/cc_full.zarr")
```
now why I am getting everything is 
```
**1. a["track"]**

array([0, 0, 0, ..., 0, 0, 0], dtype=uint32)
**2. NameError: name 'empty' is not defined**
d_a = distance(a.longitude[:-1], a.latitude[:-1], a.longitude[1:], a.latitude[1:])
d_c = distance(c.longitude[:-1], c.latitude[:-1], c.longitude[1:], c.latitude[1:])
2.d_a = cum_distance_by_track(d_a, a["track"]) / 1000.0
d_c = cum_distance_by_track(d_c, c["track"]) / 1000.0
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-31-2b0410f66012> in <module>
----> 1 d_a = cum_distance_by_track(d_a, a["track"])
      2 d_c = cum_distance_by_track(d_c, c["track"])

c:\users\hafez\miniconda3\lib\site-packages\numba\core\dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414 
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

c:\users\hafez\miniconda3\lib\site-packages\numba\core\dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359 
    360         argtypes = []

c:\users\hafez\miniconda3\lib\site-packages\numba\core\utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
NameError: name 'empty' is not defined


**3. a['n']
array([0, 0, 0, ..., 0, 0, 0], dtype=uint16)**

would you give me correction please? 
```

**Comment by AntSimi** [comment]
So if you use merge method, you will just merge observations without tracking, so you couldn't apply tracking diagnostic on it, because there are no track!

If you want path of eddies, you need to run tracking .


```python
c00.write_file(path='C:/Users/hafez/personal/python_projects/gui/eddi/',filename="cc_full.zarr",zarr_flag=False)
```

Be carefull, here you didn't store zarr because **zarr_flag=False**, [read here](https://py-eddy-tracker.readthedocs.io/en/latest/autodoc/observations.html#py_eddy_tracker.observations.observation.EddiesObservations.write_file)

**Comment by hafez-ahmad** [comment]
@AntSimi thank you so much. I appreciate your continuous advice and correction. if I am asking more, I am really sorry for that . 

I have saved identifications [ a lot of anticyclonic files and cyclonic files ],
 I guess my next step is to **run tracking and then generate med atlas over a period**
 **1. would you tell me how to run "conf.yaml" in ubuntu / any other OSs?** I am literally stuck at this stage . 
**2. how to generate files [I guess it is combined zarr files ,] for tracking diagnostic**  

although I created a combined zarr file which is not able to perform for tracking diagnostic step. 

Best Regards
hafez

**Comment by AntSimi** [comment]
Good things to have identification files:

1. It's look like a problem of path in windows, try to google it, i haven't no idea how to solve it, i work only on linux.
 The other way is to use directly python module :  [run tracking example](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/08_tracking_manipulation/pet_run_a_tracking.html#sphx-glr-python-module-08-tracking-manipulation-pet-run-a-tracking-py)
3 first code block are needed to create an atlas, just replace file_objects by a sorted list of your identification file(Anticyclonic and cyclonic, must be track in 2 separate object).

2. you must create an atlas first (do 1. step) before

**Comment by hafez-ahmad** [comment]
now, I am running it in ubuntu 20 , would you please check it ? 
 **EddyTracking conf.yaml -v DEBUG**
/home/hafez/.local/bin/EddyTracking:121: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml_load(stream)
INFO 2020-09-26 23:05:36,402 EddyTracking.browse_dataset_in :
                                        Search files : /home/hafez/eddy/anticyclonic/Anticyclonic_*.nc'INFO 2020-09-26 23:05:36,405 EddyTracking.browse_dataset_in :
                                        0 grids available
        DEBUG 2020-09-26 23:05:36,405   EddyTracking.   browse_dataset_in :
                                                Pattern date : .*c_([0-9]*?).[nz].*
INFO 2020-09-26 23:05:36,406 EddyTracking.<module> :
                                        Start tracking on 0 files
Traceback (most recent call last):
  File "/home/hafez/.local/bin/EddyTracking", line 193, in <module>
    raise Exception(
Exception: Input file number (0) is shorter than TRACK_DURATION_MIN (10).

**Comment by AntSimi** [comment]
All informations are in your first log :
```bash
INFO 2020-09-26 23:05:36,402 EddyTracking.browse_dataset_in :
                                        Search files : /home/hafez/eddy/anticyclonic/Anticyclonic_*.nc'
INFO 2020-09-26 23:05:36,405 EddyTracking.browse_dataset_in :
                                        0 grids available
```
You have no identification file which match with :  /home/hafez/eddy/anticyclonic/Anticyclonic_*.nc'

**Comment by hafez-ahmad** [comment]
@AntSimi I am very very grateful to you. I am so sorry that I waste your valuable time. I guess it will work smoothly in the Linux system. 
I can run it successfully. 

Best regards
hafez

**Comment by AntSimi** [comment]
Well done! Happy for this positiv issue. Maybe if you found answer at the current issue, close it.

**Comment by hanyangliu1002** [comment]
Hello, I would like to ask, if you want to make a cyclonic /anticyclonic nc file for a **month**, do you need to identify the eddy separately every day and then merge it ?

**Comment by hanyangliu1002** [comment]
I can output the one day cyclonic/ Anticyclonic .nc file, but how to output for more long time, such as month, year....

**Comment by hanyangliu1002** [comment]
I download the data from this https://data.aviso.altimetry.fr/aviso-gateway/data/META3.1exp_DT/META3.1exp_DT_allsat/, can we use this data to track and analyze  eddies. 
the data period is 1993/01/01 to 2020/03/07, Can we extract the time we want to study from this data

**Comment by hanyangliu1002** [comment]
I would like to ask about the livetime Histogram of the eddy in the example of the pyeddytracker document. Is his vertical axis the number of eddy? Why is there a negative power of 10?
![擷取](https://user-images.githubusercontent.com/104262092/218693745-606ddaec-025c-431e-b19c-d5b1698097ef.JPG)

**Comment by AntSimi** [comment]
please open new issue for new question
