### ISSUE TITLE
Plot for relative changes in latitude and longitude

### ISSUE THREAD

**Issue by Ashwitaa** [AntSimi/py-eddy-tracker#213]
Hi Antione,

I want to show the northward and southward direction of the anticyclonic and cyclonic vortices, shown in the figure below by Chelton et al., 2007
<img width="288" alt="Fig_Cheltonetal2007" src="https://github.com/AntSimi/py-eddy-tracker/assets/53576269/cf620835-82ca-4d72-ac32-04db5ad9b291">

Could you please assist me with how this can be done?

Thanks!

**Comment by AntSimi** [comment]
A short way to do this, but not optimize:
```python
lon, lat = c.longitude, c.latitude
for sl, _, _ in c.iter_on('track'):
    x, y = lon[sl] - lon[sl.start], lat[sl] - lat[sl.start]
    plt.plot(x,y)
```
where `c` is an object which contains cyclonic track eddies
