### ISSUE TITLE
py_eddy_tracker.dataset.grid issue

### ISSUE THREAD

**Issue by emma97956461** [AntSimi/py-eddy-tracker#218]
1 import py_eddy_tracker.dataset.grid
> 
> File ~/anaconda3/envs/env_test/lib/python3.9/site-packages/py_eddy_tracker/dataset/grid.py:10
>       8 from cv2 import filter2D
>       9 from matplotlib.path import Path as BasePath
> ---> 10 from netCDF4 import Dataset
>      11 from numba import njit, prange, types as numba_types
>      12 from numpy import (
>      13     arange,
>      14     array,
>    (...)
>      42     zeros,
>      43 )
> 
> File ~/anaconda3/envs/env_test/lib/python3.9/site-packages/netCDF4/__init__.py:3
>       1 # init for netCDF4. package
>       2 # Docstring comes from extension module _netCDF4.
> ----> 3 from ._netCDF4 import *
>       4 # Need explicit imports for names beginning with underscores
>       5 from ._netCDF4 import __doc__
> 
> ImportError: dlopen(/Users/emma/anaconda3/envs/env_test/lib/python3.9/site-packages/netCDF4/_netCDF4.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_H5get_libversion'**

Hi, I'm trying to use the pyeddytracker package but I have been encountering multiple issues when downloading: I'm working on a virtual environment with Python 3.9.6 (I tried with 3.8.18 as well), and when I attempt to import py_eddy_tracker.dataset.grid I encounter the error above.
I see that the issue is with netCDF4, so I have tried both versions 1.5.8 and 1.6.0 but nothing changes; I have also encountered a number of errors related to numpy, but for now this seems to be the sole problem.
Thank you for any help you can give,

Emma
-->

**Comment by emma97956461** [comment]
No I didn't get any error when importing netcdf4, I tried installing pyeddytracker in multiple ways:
on my local machine, both from terminal with pip and homebrew, and directly from jupyterlab.
I also work on remote machines and tried there, in the same ways. I always encountered some kind of issue when importing the dataset.grid, which is either related to numpy or netcdf4. Today I thought the problem was solved, but after restarting my kernel I find that I can't even import py_eddy_tracker anymore, because of numpy; I get the error:
AttributeError: module 'numpy' has no attribute 'ndarray'
Thank you for the help

**Comment by AntSimi** [comment]
Did you have same error if you only do env creation must install also py eddy tracker package:
```bash
conda env create --file environment.yml
conda activate binder-pyeddytracker
```

**Comment by marimpacheco** [comment]
Yes

**Comment by AntSimi** [comment]
I don't know how to solve cv2 install problem, i am not able to reproduce this pb on several platform

**Comment by ctroupin** [comment]
Hello Antoine, we got the same issue during an installation in Jupyterhub, and it seems that
```python
pip install opencv-python-headless
```
solved the issue.

**Comment by AntSimi** [comment]
thanks
