### ISSUE TITLE
The function in the library tried to use Numba to speed up the computation, but received an array of type numpy.ma.MaskedArray that is not supported by Numba.

### ISSUE THREAD

**Issue by joyyy1407** [AntSimi/py-eddy-tracker#221]
Hello, thank you very much for providing this method for you to learn, but I have the following problem when running the pet_sla_and_adt, and I have tried multiple methods and still not solved, so I came to you for help:

import os
os.environ['NUMBA_DISABLE_JIT'] = '1'
from py_eddy_tracker.dataset.grid import GridDataset
# a_adt, c_adt = g.eddy_identification("adt", "ugos", "vgos", date, 0.002)
a_sla, c_sla = g.eddy_identification("sla", "ugosa", "vgosa", date, 0.002)

NumbaTypeError: Unsupported array type: numpy.ma.MaskedArray.

**Comment by AntSimi** [comment]
Numba version is too recent for last version of py eddy tracker

**Comment by Mrvy29** [comment]
it seems to me all those issues converge to the last upgrade of numpy and the previous dependencies with py-eddy-tracker

**Comment by reillyja** [comment]
Using `pip install numba==0.55.2` fixed this error for me
