### ISSUE TITLE
error about eddy_identification function

### ISSUE THREAD

**Issue by zhanglan009** [AntSimi/py-eddy-tracker#222]
Dear Author,
When I running the eddy_identification function, I always get only 1 anticyclone and 1 cyclone, or 0 anticyclones and cyclones entirely, regardless of running the example pet_eddy_sla_and_adt you provided or the example on https://py-eddy-tracker.readthedocs.io/en/latest/grid_identification.html. I'm wondering if the eddy_identification function has been modified and is now unable to calculate all a and c.
![图片](https://github.com/AntSimi/py-eddy-tracker/assets/150409435/0248f31a-00ad-432e-a813-7346f8faa29d)
![图片](https://github.com/AntSimi/py-eddy-tracker/assets/150409435/48a22c65-bf06-42dc-b7ce-a8ac8eb3e70d)
code:
from matplotlib import pyplot as plt
from py_eddy_tracker import start_logger
from py_eddy_tracker.dataset.grid import RegularGridDataset
# start_logger().setLevel("DEBUG")  # Available options: ERROR, WARNING, INFO, DEBUG

grid_name= ('dataset-duacs-nrt-global-merged-allsat-phy-l4_1699415795667.nc')
from datetime import datetime

h = RegularGridDataset(grid_name, "longitude", "latitude", nan_masking=True)
h.bessel_high_filter("adt", 500)
date = datetime(2019, 2, 23)
h.add_uv("adt")
u, v = h.grid("u").T, h.grid("v").T
a, c = h.eddy_identification("adt","u","v",  # Variables used for identification
    date,  # Date of identification
    0.002,  # step between two isolines of detection (m)
    pixel_limit=(5, 2000),  # Min and max pixel count for valid contour
    shape_error=55,  # Error max (%) between ratio of circle fit and contour
    force_speed_unit="m/s"
)

from datetime import datetime

h = RegularGridDataset(grid_name, "longitude", "latitude", nan_masking=True)
h.bessel_high_filter("adt", 500)
date = datetime(2019, 2, 23)
h.add_uv("adt")
u, v = h.grid("u").T, h.grid("v").T
a, c = h.eddy_identification("adt","u","v",  # Variables used for identification
    date,  # Date of identification
    0.002,  # step between two isolines of detection (m)
    pixel_limit=(5, 2000),  # Min and max pixel count for valid contour
    shape_error=55,  # Error max (%) between ratio of circle fit and contour
    force_speed_unit="m/s"
)

**Comment by AntSimi** [comment]
take a look at #219

**Comment by zhanglan009** [comment]
Thank you very much! I sincerely appreciate your invaluable assistance.
