### ISSUE TITLE
Eddies detected on land

### ISSUE THREAD

**Issue by Fanny-Chenillat** [AntSimi/py-eddy-tracker#223]
Hello,
It seems that I have an issue on detection of eddies over the Mediterranean Sea using CROCO outputs. On the attached screenshot, I put the occurrence of anticyclonic eddies for observations from AVISO on top (no problem…islands are white on the figure) and for the CROCO model bellow: for example, over the Baleares Islands, there is some eddies detected (red islands), i.e., values are not null. 
I double check the model mask, which is high resolution, and islands as Baleares are well represented. This is pretty much the case for all small islands.
I have absolutely no idea where this comes from.
Did you already meet such issue? Is there is any option I forgot to mention? Maybe for the detection step?
Maybe I should mention that I actually launch the eddy detection from CROCO outputs using UnRegularGrid.
Best regards. 
Fanny Chenillat  
![Capture d'écran 2023-12-01 171932](https://github.com/AntSimi/py-eddy-tracker/assets/146865347/8d50266a-ab00-4f54-8f15-a42436d95a34)

**Comment by AntSimi** [comment]
Island are masked by nan or by a mask?

**Comment by AntSimi** [comment]
could share one croco file which produce detection over land, and how you run this detection?

**Comment by Fanny-Chenillat** [comment]
Would you mind if I send you documents by email?

**Comment by Fanny-Chenillat** [comment]
Thanks Antoine for your question that gave me a clue: it was actually necessary to mask the data (zeta in this case). 

So I replaced the 0's with nan's at the land point from sea surface level (zeta=np.where(mask_rho==0,np.nan,zeta in the locally modified eddy_identification function), and that was it: no more eddies on the Balearic islands!

Cheers!

**Comment by AntSimi** [comment]
You're welcome, I didn't do anything
