### ISSUE TITLE
Eddy detection issue

### ISSUE THREAD

**Issue by LYJ219** [AntSimi/py-eddy-tracker#227]
Hi all,

I meet a problem in following the "Eddy dection: Med", 
only two mesoscale eddies are detected which is different from the online document (as shown in the figures.

Best wishes.

![2023-12-26-fig1](https://github.com/AntSimi/py-eddy-tracker/assets/154893398/dc06d684-b2e0-41fc-a012-dd4adfe94291)
![2023-12-26-fig2](https://github.com/AntSimi/py-eddy-tracker/assets/154893398/b22c9bea-4440-420a-a52b-18057cfa004d)
![2023-12-26-fig3](https://github.com/AntSimi/py-eddy-tracker/assets/154893398/4085e7a8-fdaa-4851-bd76-6ae39ea73bb6)

**Comment by Mrvy29** [comment]
I'm having the same issue and warnings

**Comment by berzinastella** [comment]
Hi, both! 
Your issue will be solved in you uninstall the current matplotlib and install matplotlib <3.8.1.
I do `pip install matplotlib==3.7.1` and then it worked for me!
I hope it helps

**Comment by AntSimi** [comment]
Issue related #217
