### ISSUE TITLE
Request a demo for plot of the The trajectories of cyclonic  and anticyclonic eddies 

### ISSUE THREAD

**Issue by hafez-ahmad** [AntSimi/py-eddy-tracker#23]
I have already opened issues. 
**Eddy Trajectories**

I would like to request a demo of how to plot or Map of The trajectories of cyclonic and anticyclonic eddies with a particular lifetime.
for instance, I like to map all eddies with greater than or equal  1 or 3 week's lifetime. 

Best Regards
Hafez

**Comment by AntSimi** [comment]
Look at [this function ](https://py-eddy-tracker.readthedocs.io/en/latest/autodoc/observations.html#py_eddy_tracker.observations.tracking.TrackEddiesObservations.extract_with_length)

And [this example](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/08_tracking_manipulation/pet_display_track.html#sphx-glr-python-module-08-tracking-manipulation-pet-display-track-py)

**Comment by hafez-ahmad** [comment]
@AntSimi you made amazing documentation. 
1.would you add a little bit of how to plot track [cyclonic and anticyclone] with indicating origin point and decay point?

2. can I make crop or extract the densest area of cyclonic/ anticyclonic activities or how to convert it into shapefiles?

Best Regards
Hafez

**Comment by AntSimi** [comment]
Hi,

1.  Maybe look at [this for origin](https://py-eddy-tracker.readthedocs.io/en/latest/autodoc/observations.html#py_eddy_tracker.observations.observation.EddiesObservations.first_obs) and [this for death](https://py-eddy-tracker.readthedocs.io/en/latest/autodoc/observations.html#py_eddy_tracker.observations.observation.EddiesObservations.last_obs), to do selection look at [all extract function](https://py-eddy-tracker.readthedocs.io/en/latest/autodoc/observations.html#py_eddy_tracker.observations.tracking.TrackEddiesObservations.extract_first_obs_in_box)
2. The are no function to convert eddies in shapefile, if you want a contribution is welcome.
3. Look at [grid_count function](https://py-eddy-tracker.readthedocs.io/en/latest/autodoc/observations.html#py_eddy_tracker.observations.observation.EddiesObservations.grid_count)

**Comment by hafez-ahmad** [comment]
Hi,

Could you please write code for generating (4c-4e) Eddy trajectories with different life time and Fig. 3. Histograms with propagation and Fig. 5. Census statistics for the numbers of eddy centroids (top) and eddy interiors (bottom) for eddies with lifetimes ⩾16 weeks that passed through each 1° × 1° region over the 16-year period 
https://www.sciencedirect.com/science/article/pii/S0079661111000036
I really appreciate your help.
