### ISSUE TITLE
Example pet_sla_and_adt.py long line

### ISSUE THREAD

**Issue by ddd0203** [AntSimi/py-eddy-tracker#247]
Hello, author
I have encountered the same problem as some people (there are many long straight lines on the graph when running pet_sla_and_adt.py), but I have not been able to solve it using their methods, including 1. reinstalling anaconda and eddytracker 2. changing the version of Python 3. modifying file paths, etc
My current environment configuration is
Python version is:3.10.14
numpy version is:1.22.4
matplotlib version is:3.7.1
pyeddytracker version is 3.6.1
I am using the Windows system.
Besides the above methods, how can I solve this problem? Thank you very much
<img width="720" alt="a34ecd013fc70be66d0eaa806853dc2" src="https://github.com/user-attachments/assets/824f862f-3e7a-4c89-8d21-4aaf38b503dd">

**Comment by ddd0203** [comment]
By lowering the Python version to 3.6, this issue was resolved, but 3.10 is still incorrect

**Comment by AntSimi** [comment]
I think this issues is related to #130 , but i haven't window platform to test and understand this problem, any help is welcome
