### ISSUE TITLE
Any docker image or version info?

### ISSUE THREAD

**Issue by Carl-Llewellyn** [AntSimi/py-eddy-tracker#253]
I've been trying to install dependencies on Linux in a virtual env, even tried moving to a VM with a lower OS Linux, along with Windows 10. I'm getting all kinds of errors.

Any info on what versions dependencies need to be? Or a Docker file?

Thanks!

**Comment by AntSimi** [comment]
There is no docker image.
Which kind of error did you get?

**Comment by Carl-Llewellyn** [comment]
> If you use this file to create env with conda or mamba it must work https://github.com/AntSimi/py-eddy-tracker/blob/master/environment.yml

To be honest I gave up and just did my own plotting. Closing.
