### ISSUE TITLE
Eddy tracking and python3.12

### ISSUE THREAD

**Issue by ctroupin** [AntSimi/py-eddy-tracker#254]
Hello Antoine,

I've recently restarted to use the package and surprisingly with `python3.12` (in a virtual environment), I don't get the expected results: whatever domain I select, the code only detects **one** eddy.

For instance with the data provided with the code
```python
g = RegularGridDataset(
    data.get_demo_path("dt_med_allsat_phy_l4_20160515_20190101.nc"),
    "longitude",
    "latitude",
)
g.add_uv("adt")
a, c = g.eddy_identification("adt", "u", "v", datetime.datetime(2016, 5, 20), 0.001, shape_error=85, pixel_limit=(1, 50000))
```
(note that I used a large value for `shape_error` and a wide interval for `pixel_limit` so I'm sure I find eddies) and this is what I got (the eddy is visible in green):
![Screenshot from 2024-11-18 15-23-17](https://github.com/user-attachments/assets/cc17d3bf-797e-41d7-881c-ea6f5817f057)

Then I re-installed everything from scratch, again in virtual environment, but with `python3.10`, and now the results are OK:
![Screenshot from 2024-11-18 15-24-21](https://github.com/user-attachments/assets/d38750e4-c8d3-4515-9669-7a8619b5eb1e)

__Question:__ is there a specific reason why it would fail with python3.12?
(and sorry if it's in the doc and I didn't see it)

**Comment by AntSimi** [comment]
It's a known problem #217  that i didn't take time to solve, matplotlib >= 3.8 have a new object for contour that are not correctly managed by py eddy tracker.

**Comment by AntSimi** [comment]
Recently i set matplotlib version in requirements.txt to avoid this problem, before to correctly manage the upgrade of matplotlib

**Comment by ctroupin** [comment]
ok thanks, if it's known then let's close, I'll be using another Python (and `matplotlib`) versions.
