### ISSUE TITLE
Issue with tracking

### ISSUE THREAD

**Issue by mealissa** [AntSimi/py-eddy-tracker#26]
I have some issues with tracking the eddies using the command line EddyTracking tracking.yaml -v DEBUG

```bash
                                                Create Variable effective_contour_latitude
        DEBUG 2020-09-30 15:54:45,315   observation.    to_netcdf :
                                                Create Variable effective_contour_longitude
        DEBUG 2020-09-30 15:54:45,323   observation.    to_netcdf :
                                                Create Variable effective_contour_shape_error
        DEBUG 2020-09-30 15:54:45,325   observation.    to_netcdf :
                                                Create Variable effective_radius
        DEBUG 2020-09-30 15:54:45,327   observation.    to_netcdf :
                                                Create Variable inner_contour_height
        DEBUG 2020-09-30 15:54:45,329   observation.    to_netcdf :
                                                Create Variable latitude
        DEBUG 2020-09-30 15:54:45,330   observation.    to_netcdf :
                                                Create Variable latitude_max
        DEBUG 2020-09-30 15:54:45,332   observation.    to_netcdf :
                                                Create Variable longitude
        DEBUG 2020-09-30 15:54:45,333   observation.    to_netcdf :
                                                Create Variable longitude_max
        DEBUG 2020-09-30 15:54:45,335   observation.    to_netcdf :
                                                Create Variable num_contours
        DEBUG 2020-09-30 15:54:45,336   observation.    to_netcdf :
                                                Create Variable num_point_e
        DEBUG 2020-09-30 15:54:45,338   observation.    to_netcdf :
                                                Create Variable num_point_s
        DEBUG 2020-09-30 15:54:45,339   observation.    to_netcdf :
                                                Create Variable speed_average
        DEBUG 2020-09-30 15:54:45,341   observation.    to_netcdf :
                                                Create Variable speed_contour_height
        DEBUG 2020-09-30 15:54:45,343   observation.    to_netcdf :
                                                Create Variable speed_contour_latitude
        DEBUG 2020-09-30 15:54:45,350   observation.    to_netcdf :
                                                Create Variable speed_contour_longitude
        DEBUG 2020-09-30 15:54:45,358   observation.    to_netcdf :
                                                Create Variable speed_contour_shape_error
        DEBUG 2020-09-30 15:54:45,360   observation.    to_netcdf :
                                                Create Variable speed_radius
        DEBUG 2020-09-30 15:54:45,362   observation.    to_netcdf :
                                                Create Variable time
        DEBUG 2020-09-30 15:54:45,364   observation.    to_netcdf :
                                                Create Variable uavg_profile
INFO 2020-09-30 15:54:45,374 tracking.prepare_merging :
                                        9657 tracks identified
INFO 2020-09-30 15:54:45,374 tracking.prepare_merging :
                                        102672 observations will be join
        DEBUG 2020-09-30 15:54:45,374   tracking.       _copy :
                                                Copy done
Traceback (most recent call last):
  File "/usr/bin/EddyTracking", line 4, in <module>
    __import__('pkg_resources').run_script('pyEddyTracker==3.1.0+36.g2e73304', 'EddyTracking')
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.8/site-packages/pyEddyTracker-3.1.0+36.g2e73304-py3.8.egg/EGG-INFO/scripts/EddyTracking", line 237, in <module>
    SHORT_CORRESPONDANCES.shorter_than(size_max=NB_OBS_MIN)
  File "/usr/lib/python3.8/site-packages/pyEddyTracker-3.1.0+36.g2e73304-py3.8.egg/py_eddy_tracker/tracking.py", line 510, in shorter_than
    translate = empty(i_keep_track.max() + 1, dtype='u4')
  File "/usr/lib/python3.8/site-packages/numpy/core/_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity

```

This is how the script crushes. can you please assist me to solve this issue?

**Comment by AntSimi** [comment]
Hi,
May i  ask you more information to help you?
Could you share your conf.yaml.
How many detection file have you?
Antoine

**Comment by mealissa** [comment]
Hi, 
Yes of course
`PATHS:
  # Files produces with EddyIdentification
  FILES_PATTERN: /home/alissa/home2/TSTECMWF/EULER/ecmwf/out/Anticyclonic_*.nc
  SAVE_DIR: /home/alissa/home2/TSTECMWF/EULER/ecmwf/track

# Number of timestep for missing detection
VIRTUAL_LENGTH_MAX: 0
# Minimal time to consider as a full track
TRACK_DURATION_MIN: 30
`
I do have 365 detection files. One of the messages I just paid attention to is:

`
INFO 2020-10-02 10:25:29,003 tracking.track :
                                        b'/home/alissa/home2/TSTECMWF/EULER/ecmwf/out/Anticyclonic_20060110.nc' match with previous state
        DEBUG 2020-10-02 10:25:29,003   tracking.       track :
                                                2286 obs to match
        DEBUG 2020-10-02 10:25:29,360   observation.    solve_simultaneous :
                                                Shape conflict matrix : (151, 151), 329 conflicts
WARNING 2020-10-02 10:25:29,360 observation.solve_simultaneous :
                                        High number of conflict : 302 (nb_conflict)
        DEBUG 2020-10-02 10:25:29,381   observation.    solve_simultaneous :
`

**Comment by AntSimi** [comment]
Hi

Conflicts : when an eddy can be associated to several other
It's normal to have some conflicts, and i don't think it's linked with your problem.

Lot of questions:

1. Did you look at some identification file? you could do with [this](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/02_eddy_identification/pet_display_id.html), maybe display 2 or 3 consecutive identification
2. With which comand did you run identification?
3. Do you have same problem with cyclonic?
4. Do you have same problem with shorter period? (In order to create a minimal example)
5. Is it a global identification?

You error look like if you have no shorter eddy but it's strange (for 30 days).

Antoine

**Comment by mealissa** [comment]
1. Did you look at some identification file? you could do with this, maybe display 2 or 3 consecutive identification

I will do so and be back to you.

2. With which comand did you run identification?

`EddyId path_to_nc_file   ssh ugos vgos longitude latitude ./ `

3. Do you have same problem with cyclonic?

yes same issue with both.

4.  Do you have same problem with shorter period? (In order to create a minimal example)

same issue with shorter or longer


5. Is it a global identification?

yes global identification from Model data (surface)

Thank you for your quick answer

**Comment by AntSimi** [comment]
Is it a daily input file of identification? or you have only one file with all time step?
Could you share `ncdump -h` of  one input file?

**Comment by mealissa** [comment]
![2006-02-01](https://user-images.githubusercontent.com/29278776/94909287-3c226700-04a3-11eb-8432-8ce871b64926.png)
![2006-03-01](https://user-images.githubusercontent.com/29278776/94909289-3d539400-04a3-11eb-8db8-6cc958867377.png)
![2006-01-05](https://user-images.githubusercontent.com/29278776/94909291-3d539400-04a3-11eb-91c8-1ef89e59f0ca.png)

Here are some of the plots. I think I get the point. they look all alike. maybe all the identifications are coming from the first day.

yes, I do have one file with all time steps. I will probably have to seperate the "one" file into multi-files and run again.

here is the ncdump output:



`ncdump -h ecmwf.nc 
netcdf ecmwf {
dimensions:
        time_counter = UNLIMITED ; // (361 currently)
        lon = 1440 ;
        lat = 720 ;
variables:
        double time_counter(time_counter) ;
                time_counter:standard_name = "time" ;
                time_counter:long_name = "Time axis" ;
                time_counter:units = "seconds since 2006-01-03 00:00:00" ;
                time_counter:calendar = "gregorian" ;
                time_counter:axis = "T" ;
        double lon(lon) ;
                lon:standard_name = "longitude" ;
                lon:long_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
        double lat(lat) ;
                lat:standard_name = "latitude" ;
                lat:long_name = "latitude" ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
        float sst(time_counter, lat, lon) ;
                sst:standard_name = "Sea Surface temperature" ;
                sst:long_name = "Sea Surface temperature" ;
                sst:units = "C" ;
                sst:_FillValue = -9999.f ;
                sst:missing_value = -9999.f ;
                sst:interval_operation = 1200.f ;
                sst:interval_write = 432000.f ;
                sst:online_operation = "ave(x)" ;
        float ssh(time_counter, lat, lon) ;
                ssh:standard_name = "Sea Surface Height" ;
                ssh:long_name = "Sea Surface Height" ;
                ssh:units = "m" ;
                ssh:_FillValue = -9999.f ;
                ssh:missing_value = -9999.f ;
                ssh:interval_operation = 1200.f ;
                ssh:interval_write = 432000.f ;
                ssh:online_operation = "ave(x)" ;
        float ugos(time_counter, lat, lon) ;
                ugos:standard_name = "Surface zonal Current" ;
                ugos:long_name = "Surface zonal Current" ;
                ugos:units = "m/s" ;
                ugos:_FillValue = -9999.f ;
                ugos:missing_value = -9999.f ;
                ugos:interval_operation = 1200.f ;
                ugos:interval_write = 432000.f ;
                ugos:online_operation = "ave(x)" ;
        float vgos(time_counter, lat, lon) ;
                vgos:standard_name = "Surface meridional Current" ;
                vgos:long_name = "Surface meridional Current" ;
                vgos:units = "m/s" ;
                vgos:_FillValue = -9999.f ;
                vgos:missing_value = -9999.f ;
`

**Comment by AntSimi** [comment]
Ok for solution take look at issues #20 and reason are explain in #10 (i forgeted this error )

**Comment by mealissa** [comment]
Problem solved, Many thanks to you for your assistance.
