### ISSUE TITLE
eddy tracking

### ISSUE THREAD

**Issue by Kris-wu-glut** [AntSimi/py-eddy-tracker#28]
i just running the code‘’EddyTracking tracking.yaml‘’ ，there is an error occurred.
![2020-10-05 10-32-06屏幕截图](https://user-images.githubusercontent.com/66007137/95035008-353f6280-06f6-11eb-83ac-d424cc19edc1.png)

**Comment by AntSimi** [comment]
Ok, but in your short summary, i didn't see any reference at the py eddy tracker, you need to add more information.

> i just running the code‘’EddyTracking tracking.yaml‘’ ，there is an error occurred.
> ![2020-10-05 10-32-06屏幕截图](https://user-images.githubusercontent.com/66007137/95035008-353f6280-06f6-11eb-83ac-d424cc19edc1.png)
