### ISSUE TITLE
About program testing

### ISSUE THREAD

**Issue by Kris-wu-glut** [AntSimi/py-eddy-tracker#29]
Hi, I tried to test this program(pet-run-a-tracking.py) with my  dataset, but this error occurred.
![20201009215337](https://user-images.githubusercontent.com/66007137/95591497-f4d74000-0a79-11eb-9994-fbd2d44888e0.png)

**Comment by AntSimi** [comment]
Ok, it was not explicit, but `get_remote_sample('...')` was to get demo samples you must replace `file_objects` by your list of file don't mix anticyclone and cyclone

**Comment by Kris-wu-glut** [comment]
It does work to replace it with the list of file, thanks !
