### ISSUE TITLE
Match -> ZeroDivisionError

### ISSUE THREAD

**Issue by acapet** [AntSimi/py-eddy-tracker#30]
### Bug report

**Bug summary**

Obtained ZeroDivisionError while applying `match` after Identification + tracking steps achieved with bash.
Code updated (pull + install) this morning. 

**Code for reproduction**

```python
tcC = TrackEddiesObservations.load_file("../out_"+set1+"/Tracks/Cyclonic.nc")
taC = TrackEddiesObservations.load_file("../out_"+set1+"/Tracks/Anticyclonic.nc")

tcE = TrackEddiesObservations.load_file("../out_"+set2+"/Tracks/Cyclonic.nc")
taE = TrackEddiesObservations.load_file("../out_"+set2+"/Tracks/Anticyclonic.nc")

# Get indexs of close observation (based on overlap contour)
ia, ja, costa = taE.match(taC, cmin=0.01)
ic, jc, costc = tcE.match(tcC, cmin=0.01)
```

**Actual outcome**

```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-80-6939f16149e0> in <module>
      6 
      7 # Get indexs of close observation (based on overlap contour)
----> 8 ia, ja, costa = taE.match(taC, cmin=0.01)
      9 ic, jc, costc = tcE.match(tcC, cmin=0.01)

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyEddyTracker-3.2.0+43.g64ad6c0.dirty-py3.8.egg/py_eddy_tracker/observations/observation.py in match(self, other, method, intern, cmin, **kwargs)
    914                 self[x_name], self[y_name], other[x_name], other[y_name]
    915             )
--> 916             c = vertice_overlap(
    917                 self[x_name][i],
    918                 self[y_name][i],

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyEddyTracker-3.2.0+43.g64ad6c0.dirty-py3.8.egg/py_eddy_tracker/poly.py in vertice_overlap(x0, y0, x1, y1, minimal_area)
    328         # we divide intersection with polygon merging result from 0 to 1
    329         else:
--> 330             cost[i] = intersection / (p0 + p1).area()
    331     return cost
    332 

ZeroDivisionError: float division by zero
```

**Expected outcome**

I report it as a bug, because this script was going on well previously. 
The same track files are used for other processing (eg. maps of properties, comparison), without problem.

**Comment by AntSimi** [comment]
Did you compare tracking file or detection?
If it's tracking file :
- did you take care at time axis?
- did you used virtual observation?

**Comment by acapet** [comment]
I'm using Tracking files, ie. result files from the tracking script, containing eddies for an entire year. 

* I don't get what you mean by "did you take care at time axis?", could you ba a bit more specific ? 
* I have tested both with (`VIRTUAL_LENGTH_MAX: 2`, in the .yml file) and without (`VIRTUAL_LENGTH_MAX: 0`) virtual. Same result.

**Comment by acapet** [comment]
Sorry, there's a mistake in my previous comment.
 Not considering virtual eddies, ie. tracking with without (VIRTUAL_LENGTH_MAX: 0), prevents the error.

**Comment by AntSimi** [comment]
**Axis time**
I you use `match` function between your year datasets, it will search match without take care of time, so you could associate eddy from t0 with t100, ...

In order to compare only eddies from same day you could use :

```python 
for index_1, index_2, t0, t1 in dataset_1.align_on(dataset_2):
    local_d1 = dataset_1.index(index_1)
    local_d2 = dataset_2.index(index_2)
```

**Virtual and match function**
`match` function use contour to find overlap, in case of virtual , you have no defined contour(or more accurate : a contour with an area of 0), you could put a contour deduced from interpolated radius to avoid this problem.

**Comment by AntSimi** [comment]
You could now use [circle_contour method](
https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.circle_contour) with option `only_virtual=True` to set circle contour only for virtual
