### ISSUE TITLE
Eddy tracking

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#31]
Dear  Antoine,

I have a few questions related to eddy tracking:
What is the difference between different tracking criterion: default and area tracker?

And as we have an irregular dataset, then do you think it makes much difference when we do the tracking using either of the 2 tracking schemes?

I have attached our tracking result using the default tracker, where our file contains data of 5 days with a minimum track duration of 3 days.
where in the figure (attached),
the filled contours are the contours of vorticity (vrt_2) in the background and the contour lines are the detections using py-eddy-tracker.
Could you please tell us why we see (in the attached figure) the eddy in box 1 in both 'untracked' and 'tracked' files?
and same for box2 and box3.

Thank you.

Best Regards,
Ashwita

<img width="897" alt="tracking_at_1500mDepth" src="https://user-images.githubusercontent.com/53576269/96864885-6bf0d900-1469-11eb-8962-b58473f9800f.png">

**Comment by AntSimi** [comment]
First tracking use only detection file, it doesn't care of grid format

# General information
`area_tracker` associate observations only if there is an overlap greater than 20 % between contour of observations (use effective/outter contour)
[Code for area tracker here](https://py-eddy-tracker.readthedocs.io/en/latest/_modules/py_eddy_tracker/featured_tracking/area_tracker.html#AreaTracker.tracking)
[Match function](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.match)
[overlap function](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.poly.vertice_overlap.html#py_eddy_tracker.poly.vertice_overlap)

`default tracker` is based on distance between observations center, and check if amplitude and radius are close (maximal factor of 2.5 between the two observations)

Now, i use only AreaTracker which are more able to follow eddies during merging/spliting events.

# General questions:

1. Which tracker did you use it for those figures?
2. How many days are display? 5 or more ?

# Case
I guess yaml was set like that
```yaml
PATHS:
  # Files produces with EddyIdentification
  FILES_PATTERN: MY_IDENTIFICATION_PATH/Anticyclonic*.nc #(5 files)
  SAVE_DIR: MY_OUTPUT_PATH
# Number of timestep for missing detection
VIRTUAL_LENGTH_MAX: 0
# Minimal time to consider as a full track
TRACK_DURATION_MIN: 3
```

- **Case 3** : i didn't see your identification file, but i think there are days between the untracked observation and the short track, maybe if you use VIRTUAL_LENGTH_MAX option you will join those observations, this options allow missing detection between few days
- **Case 1** :  How did you do display? Currently i wonder why i saw only one contour on track subplot(top left)
- **Case 2** :  Like case 1 i need more informations to understand, maybe you could share identification files and tracking configuration and tracking atlas?

You have some general informations about tracking [here](https://py-eddy-tracker.readthedocs.io/en/latest/run_tracking.html).

**Comment by Ashwita2619** [comment]
I used 'default tracker' with display of only 5 days for the figures I have attached before.
Yes, the yaml file is set like the way you've mentioned above.

How did I do the display?:--- By using effective contours in lat and lon

I also have made few tests using different regions and in some cases I see results like Case01 and Case02.

I have attached the identification and tracking files, and the tracking atlas.

[files.zip](https://github.com/AntSimi/py-eddy-tracker/files/5480718/files.zip)

**Comment by AntSimi** [comment]
Before to look at tracking, i do a quick look on identifcation files:
```python 
from matplotlib import pyplot as plt
from py_eddy_tracker.observations.observation import EddiesObservations
from glob import glob
from os import path
import pylook
fig = plt.figure(figsize=(10,11))
ax = fig.add_axes([.05,.05,.9,.9], projection='plat_carre')
ax.set_xlim(-100,30), ax.set_ylim(-60,75), ax.grid()
anticyclones = glob('files/identification_files/A*.nc')
cyclones = glob('files/identification_files/C*.nc')
for f in anticyclones:
    EddiesObservations.load_file(f).display(ax, color='r', ref=-100, label=path.basename(f))
for f in cyclones:
    EddiesObservations.load_file(f).display(ax, color='b', ref=-100, label=path.basename(f))
ax.legend()
fig.savefig('display.png')
```
![image](https://user-images.githubusercontent.com/36040805/97980175-a85cf700-1dd0-11eb-9c99-5ab23c035f70.png)

I am surprised to see so few eddies in atlantic ocean. I will look at tracking step

**Comment by Ashwita2619** [comment]
I forgot to inform, that the eddies what we see here are at 1500 m depth.

**Comment by AntSimi** [comment]
- **Case 1** :
There is a jump between to structure (due to weakness of default tracker) which are a mix of distance, radius similarity and amplitude similarity, [default cost fuction code](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.cost_function)
![image](https://user-images.githubusercontent.com/36040805/97989922-86b73c00-1ddf-11eb-8283-d898482c7d13.png)
There are to missing detection (9/7/2007 and 11/7/2007)
But only one observation was used in a path and the other go in untracked: **My advice change tracker and use AreaTracker**
```python
from matplotlib import pyplot as plt
from py_eddy_tracker.observations.tracking import TrackEddiesObservations
import pylook
fig = plt.figure(figsize=(10,10))
ax = fig.add_axes([.075,.075,.85,.85], projection='plat_carre')
ax.set_xlim(-12,-9), ax.set_ylim(37,40), ax.grid()

d = TrackEddiesObservations.load_file('files/tracking_files/Cyclonic.nc')
d.plot(ax, ref=-100, label='Cyclonic path')
d.display(ax, ref=-100, label='Cyclonic contour', extern_only=True)
m = d.scatter(ax, d.time - 21000, ref=-100)
c=plt.colorbar(m, cax=fig.add_axes([0.94, 0.05, 0.01, 0.9]))
ax.legend()
fig.savefig('display_case1.png')


```
![image](https://user-images.githubusercontent.com/36040805/97991194-612b3200-1de1-11eb-9de5-34cdb0e7213c.png)

- **Case 2** :
Similar to case 1 but with more complexity, again change tracker to areaTracker will avoir this type of problem
```python
from matplotlib import pyplot as plt
from py_eddy_tracker.observations.tracking import TrackEddiesObservations
import pylook
fig = plt.figure(figsize=(10,10))
ax = fig.add_axes([.075,.075,.85,.85], projection='plat_carre')
ax.set_xlim(-12.5,-9.5), ax.set_ylim(34,37), ax.grid()

d = TrackEddiesObservations.load_file('files/tracking_files/Anticyclonic.nc')
d.plot(ax, ref=-100, label='Cyclonic path')
d.display(ax, ref=-100, label='Cyclonic contour', extern_only=True)
m = d.scatter(ax, d.time - 21000, ref=-100)
c=plt.colorbar(m, cax=fig.add_axes([0.94, 0.05, 0.01, 0.9]))
ax.legend()
fig.savefig('display_case2.png')
```
![image](https://user-images.githubusercontent.com/36040805/97992086-810f2580-1de2-11eb-86d3-47530a89d814.png)


- **Case 3** : 
there are a missing detection on 9/7/2007, use virtual will allow to link all the observations together
![image](https://user-images.githubusercontent.com/36040805/97988350-21624b80-1ddd-11eb-944f-34f2fac67c6b.png)

**Comment by AntSimi** [comment]
In summary maybe use AreaTracker and virtual (set maybe between 1 to5 days, to avoid missing detection)

**Comment by Ashwita2619** [comment]
Hello  Antoine,

Could you please help me in understanding the difference between:
'untracked' and 'track_too_short' files?…
