### ISSUE TITLE
py eddy tracker multifile analysis

### ISSUE THREAD

**Issue by abhijithpkurian** [AntSimi/py-eddy-tracker#4]
Dear Sir 

I wish to use py-eddy-tracker for the arabian sea. I wish to know how to employ the same for multiple file format for time series analysis. It would be great if you can comment upon the same with a sample code.

**Comment by AntSimi** [comment]
Hi,
I am not sure to understand your request.
What did you mean by multiple file format?
Could you explain more about your work?

Antoine

Le mer. 11 mars 2020 à 07:02, abhijithpkurian <notifications@github.com> a
écrit :

**Comment by abhijithpkurian** [comment]
i mean time series AVISO data and that to only for a particular region from
global dataset. I am not able to use the xarray function for selecting
(slicing) th region. It would be great if you can share a sample code.
Thank you

Kurian

**Comment by AntSimi** [comment]
Hi,
Py eddy tracker is designed to detect on the whole grid which are used in
input, there no tools in py eddy tracker to subset grid(you could use NCO
tools for that).
In my mind it's better to use on whole grid (global or not):

   1. if you reduce area you will have filter artefact near the bounds
   2. Eddies on the bounds of your area will be more accurate

I think it's better to detect on the whole grid, and subset on your area
after detection process.You could do that with EddySubSetter tools (which
are provide in pet module).

Antoine



Le jeu. 12 mars 2020 à 10:31, abhijithpkurian <notifications@github.com> a
écrit :

> i mean time series AVISO data and that to only for a particular region from
> global dataset. I am not able to use the xarray function for selecting
> (slicing) th region. It would be great if you can share a sample code.
> Thank you
>
> Kurian
>

**Comment by abhijithpkurian** [comment]
I sincerely thankyou for the time you spend and request your support in
long run
Thank you

Kurian

**Comment by abhijithpkurian** [comment]
Dear Sir

It would be great if you can give an example(script) of a 10 day data
analysis script since the provided in the github is a single day analysis
example script. Thank you


Kurian

**Comment by AntSimi** [comment]
Hi,
I don't know the exact format or your file.
But when i need to do that i wrote a bash script, in the actual version of py-eddy-tracker there no direct command to do that.
Or you could use a python script like that with some correction on varname and filename and date:
```python
from glob import glob
filenames =glob('.......')

for filename in filenames:
    from datetime import datetime
    h = RegularGridDataset(filename, lon_name, lat_name)
    h.bessel_high_filter('adt', 500, order=3)
    date = datetime(2019, 2, 23)
    a, c = h.eddy_identification(
        'adt', 'ugos', 'vgos', # Variables used for identification
        date, # Date of identification
        0.002, # step between two isolines of detection (m)
        pixel_limit=(5, 2000), # Min and max pixel count for valid contour
        shape_error=55, # Error max (%) between ratio of circle fit and contour
        )
    with Dataset(date.strftime('share/Anticyclonic_%Y%m%d.nc'), 'w') as h:
        a.to_netcdf(h)
    with Dataset(date.strftime('share/Cyclonic_%Y%m%d.nc'), 'w') as h:
        c.to_netcdf(h)
```

Antoine

**Comment by abhijithpkurian** [comment]
Dear Sir

I am using a similar format but I am not able to sort out with the date as
i have to deal daily netCDF4 files for one year how can Ichange the date on
each iteration. Thank you

Kurian

**Comment by AntSimi** [comment]
Maybe, you could do with:
```python
from datetime import datetime
for filename in filenames:
     date = datetime.strptime('...blabla_20180101.nc', '...blabla_%Y%m%d.nc')
```

Antoine

**Comment by abhijithpkurian** [comment]
Dear Sir

Thank you for your cooperation. I will get back to you after making a
check. Thank you

Kurian

**Comment by abhijithpkurian** [comment]
Dear Sir

Will it be possible to use the same code as mentioned to be used for a
particular region. Is there any options which can be incorporated into the
script for a regional analysis(Example: Arabian Sea). Can something be done
in the eddy_identification.yaml or within the script itself. Thank you

Kurian

**Comment by abhijithpkurian** [comment]
Is there any way that I can limit it to a basin range either the
identification or tracking.

**Comment by abhijithpkurian** [comment]
Dear Sir

A humble request my study is confined to bay of bengal will it be possible
to limit the identification and tracking within the basinal scale. It would
be great if you can help me sort out with this. Thanking you

kurian

**Comment by evanmason** [comment]
One way to do this is to make subsets of the input files (you can use NCO tools for example: http://nco.sourceforge.net/) focusing on the region you are interested in.  But as pointed out above, we recommend using the full grid and then the EddySubSetter tools module.

**Comment by abhijithpkurian** [comment]
But can the subsetting be done for the entire dataset from 1993 to
recent.after the complete detection and tracking.


And is there any sample code on subsetting since it is not provided in the
documentation.


Thank you
