### ISSUE TITLE
Quiver plots of eddies' center translation speed

### ISSUE THREAD

**Issue by acapet** [AntSimi/py-eddy-tracker#40]
Hello, 

I'm trying to use the PET modules to obtain a quiver plot of the translation velocity for eddies' centers.

First, I defined `dx_to next` and `dy_to_next` functions, modified from `TrackEddiesObservation.distance_to_next`

```
def dx_to_next(s):
    d = distance(
        s.longitude[:-1],
        s.latitude[:-1],
        s.longitude[1:],
        s.latitude[-1:],
        )
    d[s.index_from_track[1:] - 1] = 0
    d_ = np.empty(d.shape[0] + 1, dtype=d.dtype)
    d_[:-1] = d
    d_[-1] = 0
    return d_

def dy_to_next(s):
    d = distance(
        s.longitude[:-1],
        s.latitude[:-1],
        s.longitude[:-1],
        s.latitude[1:],
        )
    d[s.index_from_track[1:] - 1] = 0
    d_ = np.empty(d.shape[0] + 1, dtype=d.dtype)
    d_[:-1] = d
    d_[-1] = 0
    return d_
```

I thus obtain 

```
a = TrackEddiesObservations.load_file("../out_"+set1+"/Tracks_Overlap/Anticyclonic.nc")
dx=dx_to_next(a)
dy=dy_to_next(a)
```
Now I'd like to add dx, and dy as other fields, along the other properties such as 'amplitude', etc ..
This in order to use `grid_stat`, or others afterwards.

But it seems I can't find out how to use `add_fields` properly to do so. 

Any help, or alternative suggestions (I'd still like to know how to use add_fields) ?

Thanks

**Comment by AntSimi** [comment]
Hi,
You could look [here](https://github.com/AntSimi/py-eddy-tracker/blob/40ce202feefa349b65aac0d2d5fe56fad1fc7f82/src/py_eddy_tracker/observations/tracking.py#L126) to see an example of use. 
`add_fields` will create a new dataset with the new field which must be filled.

Nevertheless several method like [grid_stat](https://github.com/AntSimi/py-eddy-tracker/blob/40ce202feefa349b65aac0d2d5fe56fad1fc7f82/src/py_eddy_tracker/observations/observation.py#L2012) accept field name or array with same size than dataset.

Antoine

**Comment by acapet** [comment]
Thanks, 

But `a2 =    a.add_fields(("dx",))` throws the following error. 

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-18-03c8205ef183> in <module>
----> 1 a2=a.add_fields(("dx",))

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyEddyTracker-3.3.0+4.g40ce202.dirty-py3.8.egg/py_eddy_tracker/observations/observation.py in add_fields(self, fields, array_fields)
    316         """
    317         nb_obs = self.obs.shape[0]
--> 318         new = self.__class__(
    319             size=nb_obs,
    320             track_extra_variables=list(

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyEddyTracker-3.3.0+4.g40ce202.dirty-py3.8.egg/py_eddy_tracker/observations/tracking.py in __init__(self, *args, **kwargs)
     66 
     67     def __init__(self, *args, **kwargs):
---> 68         super().__init__(*args, **kwargs)
     69         self.__first_index_of_track = None
     70         self.__obs_by_track = None

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyEddyTracker-3.3.0+4.g40ce202.dirty-py3.8.egg/py_eddy_tracker/observations/observation.py in __init__(self, size, track_extra_variables, track_array_variables, array_variables, only_variables, raw_data)
    162         for elt in self.elements:
    163             if elt not in VAR_DESCR:
--> 164                 raise Exception("Unknown element : %s" % elt)
    165         self.observations = zeros(size, dtype=self.dtype)
    166         self.sign_type = None

Exception: Unknown element : dx

**Comment by acapet** [comment]
and (for the second suggestion) 

```
extent = [27, 42, 40.5, 47]
bins = ((extent[0], extent[1], step), (extent[2], extent[3], step))
g = a.grid_stat(bins, dx)
```
also cause some troubles : 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-d473322b8bc3> in <module>
----> 1 g = a.grid_stat(bins, dx)

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyEddyTracker-3.3.0+4.g40ce202.dirty-py3.8.egg/py_eddy_tracker/observations/observation.py in grid_stat(self, bins, varname, data)
   2010         x0 = bins[0][0]
   2011         x, y = (self.longitude - x0) % 360 + x0, self.latitude
-> 2012         data = self[varname] if data is None else data
   2013         if hasattr(data, "mask"):
   2014             m = ~data.mask

~/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pyEddyTracker-3.3.0+4.g40ce202.dirty-py3.8.egg/py_eddy_tracker/observations/observation.py in __getitem__(self, attr)
    286         if attr in self.elements:
    287             return self.obs[attr]
--> 288         elif attr in VAR_DESCR_inv:
    289             return self.obs[VAR_DESCR_inv[attr]]
    290         elif attr in ("lifetime", "age"):

TypeError: unhashable type: 'numpy.ndarray'
----------------------------------------
although i have 

```
print(dx.shape)
print(a["radius_e"].shape)
print(type(dx))
print(type(a["radius_e"]))
```

(26853,)
(26853,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

**Comment by AntSimi** [comment]
Ok sorry i answered too quickly.
So for [grid_stat method](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.grid_stat) use `data` option, in this case if you provide only varname the assumption is ouput grid name will be same than eddies dataset, if you use `data` option you could choose a name different for output grid and dataset variable.
For your second problem (i didn't think about that yesterday) actually you could only add [known variable](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/__init__.py#L97) to be able to convert in netcdf and other things, ...
Antoine

**Comment by acapet** [comment]
Solved. For those interested, here's how it was done : 

```
extent = [27, 42, 40.5, 47]
step = 0.25
bins = ((extent[0], extent[1], step), (extent[2], extent[3], step))

def dx_to_next(s):
    d = distance(
        s.longitude[:-1],
        s.latitude[:-1],
        s.longitude[1:],
        s.latitude[:-1],
        )
    d[s.longitude[1:]<s.longitude[:-1]] = - d[s.longitude[1:]<s.longitude[:-1]]
    d[s.index_from_track[1:] - 1] = 0
    d_ = np.empty(d.shape[0] + 1, dtype=d.dtype)
    d_[:-1] = d/86400
    d_[-1] = 0
    return d_

def dy_to_next(s):
    d = distance(
        s.longitude[:-1],
        s.latitude[:-1],
        s.longitude[:-1],
        s.latitude[1:],
        )
    d[s.latitude[1:]<s.latitude[:-1]] = - d[s.latitude[1:]<s.latitude[:-1]]
    d[s.index_from_track[1:] - 1] = 0
    d_ = np.empty(d.shape[0] + 1, dtype=d.dtype)
    d_[:-1] = d/86400
    d_[-1] = 0
    return d_


a = TrackEddiesObservations.load_file("../out_"+set1+"/Tracks_Overlap/Anticyclonic.nc")
a.position_filter(median_half_window=1, loess_half_window=5)

dxa=dx_to_next(a)
dya=dy_to_next(a)

ga = a.grid_stat(bins, varname='dx', data=dxa)
gay = a.grid_stat(bins, varname='dy', data=dya)
ga.add_grid("dy", gay.vars['dy'])

X=np.arange(bins[0][0]+bins[0][2]/2,bins[0][1]-bins[0][2]/2,bins[0][2])
Y=np.arange(bins[1][0]+bins[1][2]/2,bins[1][1]-bins[1][2]/2,bins[1][2])
[X,Y]=np.meshgrid(X,Y)

f = plt.figure(figsize=(12,10))

ax = start_axes("Anticyclonic dx", fig=f, sp='221')
m = ga.display(ax,name='dx', **kwargs_q)
update_axes(ax, m)

ax = start_axes("Anticyclonic dy", fig=f, sp='222')
m = ga.display(ax,name='dy', **kwargs_q)
update_axes(ax, m, 'm/s')

ax = start_axes("Anticyclonic Quiver", fig=f, sp='212')
Q=ax.quiver(x=X, y=Y, u=ga.vars['dx'].T, v=ga.vars['dy'].T,transform=ccrs.PlateCarree())
ax.quiverkey(Q=Q, X=.8, Y=.8, U=0.05, label='0.05 m/s', labelpos='E', coordinates="axes")


```
