### ISSUE TITLE
TrackEddiesObservations and d.to_netcdf 'handler'

### ISSUE THREAD

**Issue by evanmason** [AntSimi/py-eddy-tracker#47]
I used the loess filter on my radius tracks, but when I tried to save the filtered radii with `d.to_netcdf` I got this error:
```
In [5]: %run make_BlackSea_loess_radii.py
--- filtering ...
--- writing to nc ...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/users/e/m/emason/BS_code/make_BlackSea_loess_radii.py in <module>
     51     d.loess_filter(half_window=half_window, xfield='time', yfield='radius_s')
     52     print('--- writing to nc ...')
---> 53     d.to_netcdf(filename=filename)

TypeError: to_netcdf() missing 1 required positional argument: 'handler'
```
I am not sure what the correct argument should be?

I tried also with just `d.to_netcdf(filename)` but that gave a different error.  The previous saving method that worked for me was `d.write_netcdf(filename=filename)`, but that appears to have been changed to `to_netcdf`.  What am I doing wrong?

**Comment by AntSimi** [comment]
I think you need this method [write_file](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.write_file), this method will allow to write netcdf or zarr.
[to_netcdf](https://py-eddy-tracker.readthedocs.io/en/latest/_modules/py_eddy_tracker/observations/observation.html#EddiesObservations.to_netcdf) method need an netcdf handler like `Dataset('my.nc', 'w')`.

**Comment by evanmason** [comment]
Perfect, thanks!
