### ISSUE TITLE
Filtering out first time step

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#57]
Hello Antoine,
Could you please suggest to me, what could be the best possible way to discard (filter) eddies/tracks existing in the first time step of the analysis period?

**Comment by AntSimi** [comment]
You could use EddySubSetter tool to create a new atlas with only track which start after first day and ended before last day.
```bash
EddySubSetter \
    --period {First day + 1 in julian day(day from 1950/1/1)} {Last day - 1 in julian day(day from 1950/1/1)} \
    --full_path {atlas} {new_atlas}
```
You must replace all value between '{}'.
`full_path` option will allow to keep only track which are fully in specified period. 

You could do same things in python with your values

```python
from py_eddy_tracker.observations.tracking import TrackEddiesObservations
c = TrackEddiesObservations.load_file("Cyclonic.nc")
c_subset = c.extract_with_period(
    (20000,25000),
    full_path=True)
c_subset.write_file(filename='my_dataset.nc')
```

You could found examples in [gallery](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/index.html)
and more information about [API could be found here for TrackEddiesObservations ](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.tracking.TrackEddiesObservations.html#py_eddy_tracker.observations.tracking.TrackEddiesObservations)

**Comment by Ashwita2619** [comment]
Thank you :)

**Comment by Ashwita2619** [comment]
Could you please tell me what full_path exactly do?

**Comment by AntSimi** [comment]
'full_path' option will return the whole track even if only one part are selected by criterion [API doc](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.observations.tracking.TrackEddiesObservations.html#py_eddy_tracker.observations.tracking.TrackEddiesObservations.extract_with_mask).
So it was not the good option for you, correct option is 'remove_incomplete', :( sorry.
All trajectory which have outside observations of your period will be fully removed.
Antoine

**Comment by Ashwita2619** [comment]
full_path = False,
works as well for the filtering the files!

do you recommend to use 'full_path=false' or should I just go for 'remove_incomplete'?

**Comment by AntSimi** [comment]
Hi,
With the last message, i am not sure i understood original question.
I understood you would remove all track where you don't know if there are really born at first date or really dead(and not just stopped) at last date.
So my advice was to select all data between first_date + 1 and last_date -1 and remove with `remove_incomplete=True` option all the track which are partially selected with date filtering.

Note:
`full_path=False` is default value

**Comment by Ashwita2619** [comment]
okay.
Thanks :)
