### ISSUE TITLE
How to loop on time in a file?

### ISSUE THREAD

**Issue by ctroupin** [AntSimi/py-eddy-tracker#60]
Hello,

I am working on netCDF files that have different times inside the file, so the situation is slightly different from the AVISO file (one time per file). How can we specify which time index we want to process? 

The SSH variable is as follows:
```bash
short XE(time, nj, ni) ;
		XE:long_name = "sea surface height" ;
		XE:standard_name = "sea_surface_height_above_sea_level" ;
		XE:units = "m" ;
		XE:coordinates = "latitude longitude" ;
		XE:scale_factor = 0.001525925f ;
		XE:add_offset = 0.f ;
		XE:valid_min = -32767s ;
		XE:valid_max = 32767s ;
		XE:_FillValue = -32768s ;
```
and the time:
```bash
	double time(time) ;
		time:long_name = "time in seconds (UT)" ;
		time:standard_name = "time" ;
		time:units = "seconds since 1900-01-01T00:00:00Z" ;
		time:axis = "T" ;
		time:time_origin = "01-JAN-1900 00:00:00" ;
		time:conventions = "relative number of seconds with no decimal part" ;
```

To perform an identification, I use:
```python
date = datetime(2015, 1, 1, 0)
a, c = h.eddy_identification('XE', 'Uvel', 'Vvel', date, 0.002, pixel_limit=(5, 2000), shape_error=55)
```

Probably you already have an example but I cannot find it.

**Comment by AntSimi** [comment]
You could manage that with 'indexs' options when you load grid data, by default you get the first grid.
if you specify index for time axis, you will setup your object with the asked step
```python
h = RegularGridDataset(grid_name, lon_name, lat_name, indexs=dict(time=18))
```

[Here documentation of GridDataset which are parent class of RegularGridDataset](https://py-eddy-tracker.readthedocs.io/en/latest/_autosummary/py_eddy_tracker.dataset.grid.GridDataset.html#py_eddy_tracker.dataset.grid.GridDataset)

**Comment by ctroupin** [comment]
fine! Arthur send me an example as well, it seems quite direct, I will test that.
Thanks.
