### ISSUE TITLE
Untracked and Track_too_short

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#82]
Hi Antoine,

Could you please help me in understanding the difference between:
'untracked' and 'track_too_short' files?…

**Comment by AntSimi** [comment]
Untracked - > all eddies identified with no association with tracking, could be false detection or very quick event or could be explain by a worse tracking algorithm

Too short - > eddies identified and follow with tracking but only few days under the track_duration_min limit.
