### ISSUE TITLE
Eddy tracking on 3-hourly files

### ISSUE THREAD

**Issue by ctroupin** [AntSimi/py-eddy-tracker#92]
Hello,

I'm applying the tracking on model outputs with a time step of 3 hours. The detection gave files such as:
```
Anticyclonic_20190101000000.nc
Anticyclonic_20190101030000.nc
...
Cyclonic_20191231180000.nc
Cyclonic_20191231210000.nc
```
on which I apply `EddyTracking conf.yaml`

## 1st issue (solved)
```
...
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: 210000
```
the problem came from the fact that the tracker was expecting files with `year-month-day`.

### Solution (bad)
I hard-coded the `date_model` as `"%Y%m%d%H%M%S"` in [eddies.py](https://github.com/AntSimi/py-eddy-tracker/blob/master/src/py_eddy_tracker/appli/eddies.py#L307). 

**Question:** how could I do it in a cleaner way?

## 2nd issue

I re-run  `EddyTracking conf.yaml`, it works for some periods of time, for example if I only take `FILES_PATTERN: /data/CAPCO/EddyTracking/CORSE400/Cyclonic_201902*.nc` and I get the output as specified. However for some periods, the tracking stops with this message:

```
Traceback (most recent call last):
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/bin/EddyTracking", line 8, in <module>
    sys.exit(eddies_tracking())
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/py_eddy_tracker/appli/eddies.py", line 206, in eddies_tracking
    track(
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/py_eddy_tracker/appli/eddies.py", line 325, in track
    c.track()
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/py_eddy_tracker/tracking.py", line 385, in track
    i_previous, i_current, association_cost = self.previous_obs.tracking(
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/py_eddy_tracker/featured_tracking/area_tracker.py", line 46, in tracking
    i_self, i_other = self.solve_function(cost_mat)
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/py_eddy_tracker/observations/observation.py", line 1431, in solve_function
    return numba_where(self.solve_simultaneous(cost_matrix))
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/py_eddy_tracker/observations/observation.py", line 1331, in solve_simultaneous
    max_links = max(self_links.max(), other_links.max())
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/numpy/core/_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity 
```
I check visually that the detection worked properly and I suspect the failure is due to the fact that in my application the anticyclonic eddies are really intermittent and not frequent (just popping up once in a while)
![eddy_20190314_0900](https://user-images.githubusercontent.com/11868914/122030544-299c5380-cdce-11eb-8107-9f06ceb4ac6e.jpg)

**Question:** is this a plausible explanation and if yes, maybe is possible to have a more explicit error message?

This is the `.yaml` I use:
```
PATHS:
  # Files produces with EddyIdentification
  FILES_PATTERN: /data/CAPCO/EddyTracking/CORSE400/Cyclonic_201903*.nc
  SAVE_DIR: /data/CAPCO/EddyTracking/CORSE400/Tracking

# Number of timestep for missing detection
VIRTUAL_LENGTH_MAX: 24 # 24 X 3 hours = 72 hours = 3 days
# Minimal time to consider as a full track
TRACK_DURATION_MIN: 10

CLASS:
    MODULE: py_eddy_tracker.featured_tracking.area_tracker
    CLASS: AreaTracker
    OPTIONS:
      cmin: 0.2               
```

**Comment by AntSimi** [comment]
First note that:
Time is stored in days, detection will produce file but time information will be truncated in file ...
It's something that i note here to be change:
- https://github.com/AntSimi/py-eddy-tracker/projects/2#card-57277009

Did you have time step with 0 detection?

**Comment by ctroupin** [comment]
yes, several step with zero detection. I previously modified the parameters for the detection but in some case it seems there is no anticyclonic eddy at all (region is small as you can see).

**Comment by AntSimi** [comment]
ok, i never think to this case, i will need add some test, could you share few anticyclonic identification files which will produce this error?

**Comment by ctroupin** [comment]
yes, sure, I'll make available some files so you can test.
Can you try to download from https://dox.ulg.ac.be/index.php/s/ZURPp1BeGP2PZ5I  ?

Following your comment, I've also seen that the time is not correct in the identification files, since, for a given day, the time is the same, whatever the time of the day. I've modified the files so the time is correct but that doesn't solve the issue, just the error message is different.

**Comment by AntSimi** [comment]
I run tracking on your anticyclonic data, i solve some problems, just issues before to save remain due too of no track longer than 10 days. 

To fully resolve your issue, we will need to do:

- [ ] Allow a time precision in minutes (a little bit of work to check impact on whole algorithm)
- [ ] Manage case of very sparse detection (Could be quick)

**Comment by ctroupin** [comment]
Thanks. 
Concerning the time precision, what I did is to edit the files produced by the eddy detection:
1. deleting the time variable (with `nco`)
2. re-creating a new time variable (with python `netCDF4`) that stores the correct time (with hours, minutes and seconds) that I get from the file name.
Not very clever but at the same time easy to do, so I can test the code with the new files.

**Comment by AntSimi** [comment]
I do some modification to manage sparse detection and precise time in branch `time_float`
[Here a warning about mix new and old format](https://github.com/AntSimi/py-eddy-tracker/blob/time_float/CHANGELOG.rst#changed)

**Comment by ctroupin** [comment]
ok great!
I'm now running again the detection to ensure I don't mix old and new formats.
The times values are not correct in the netCDF files (i.e. with hours included).

Strangely, `ncdump` issues strange things but that's probably a bug on their side:
```
ncdump -v time -t Cyclonic_20190301090000.nc
...
time = "ݰ@�", "ݰ@�"", "ݰ@�""", "ݰ@�"""", "ݰ@�""""", "ݰ@�"""""" ;
```

**Comment by AntSimi** [comment]
if you don't use `-t` options you will see second from 1950-01-01, i just discover this options of ncdump, maybe there are some attributes missing for correct interpretation, it's something that i wan't to understand

**Comment by ctroupin** [comment]
yes, we don't need to worry about that, just a detail.

**Comment by ctroupin** [comment]
OK I've now run a new detection for one month (March 2019), then applied the tracking, both with the code from the `time_float` branch. 

The detection gave the same results than my last try (which was performed with version `v3.3.0`), which is always reassuring.       
The tracking gave the same issue as before:
```python
Traceback (most recent call last):
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/bin/EddyTracking", line 33, in <module>
    sys.exit(load_entry_point('pyEddyTracker==3.4.0+37.ge1eadbd', 'console_scripts', 'EddyTracking')())
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/pyEddyTracker-3.4.0+37.ge1eadbd-py3.8.egg/py_eddy_tracker/appli/eddies.py", line 206, in eddies_tracking
    track(
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/pyEddyTracker-3.4.0+37.ge1eadbd-py3.8.egg/py_eddy_tracker/appli/eddies.py", line 331, in track
    c.track()
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/pyEddyTracker-3.4.0+37.ge1eadbd-py3.8.egg/py_eddy_tracker/tracking.py", line 385, in track
    i_previous, i_current, association_cost = self.previous_obs.tracking(
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/pyEddyTracker-3.4.0+37.ge1eadbd-py3.8.egg/py_eddy_tracker/featured_tracking/area_tracker.py", line 46, in tracking
    i_self, i_other = self.solve_function(cost_mat)
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/pyEddyTracker-3.4.0+37.ge1eadbd-py3.8.egg/py_eddy_tracker/observations/observation.py", line 1435, in solve_function
    return numba_where(self.solve_simultaneous(cost_matrix))
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/pyEddyTracker-3.4.0+37.ge1eadbd-py3.8.egg/py_eddy_tracker/observations/observation.py", line 1335, in solve_simultaneous
    max_links = max(self_links.max(), other_links.max())
  File "/home/ctroupin/Software/PythonEnvs/EddyCorsica/lib/python3.8/site-packages/numpy/core/_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
```

I've put the new data files here: https://dox.ulg.ac.be/index.php/s/1j8Fck35Ge5Nes8 if it can help. The figure below are the eddies detected for that period (March 2019)

![eddies_corse400_test_03](https://user-images.githubusercontent.com/11868914/122376447-73b73d80-cf64-11eb-9810-b45aa5eb1c1a.png)

**Comment by AntSimi** [comment]
I missing a section in my previous commit :(.

This 2 options count obs, it must be clarify in documentation, if you have a timestep different of 1 days, you must take into account like you do for `VIRTUAL_LENGTH_MAX`
```yaml
# Number of timestep for missing detection
VIRTUAL_LENGTH_MAX: 24 # 24 X 3 hours = 72 hours = 3 days
# Minimal time to consider as a full track
TRACK_DURATION_MIN: 10
```

**Comment by AntSimi** [comment]
> ok great!
> I'm now running again the detection to ensure I don't mix old and new formats.
> The times values are not correct in the netCDF files (i.e. with hours included).
> 
> Strangely, `ncdump` issues strange things but that's probably a bug on their side:
> 
> ```
> ncdump -v time -t Cyclonic_20190301090000.nc
> ...
> time = "ݰ@�", "ݰ@�"", "ݰ@�""", "ݰ@�"""", "ݰ@�""""", "ݰ@�"""""" ;
> ```

When ncdump try to translate date, it didn't take in account scale_factor...

**Comment by ctroupin** [comment]
ok, the code is now running without any error! 
The tracking on cyclonic eddies generated 4 files:
```bash
Cyclonic_correspondances.nc
Cyclonic.nc
Cyclonic_track_too_short.nc
Cyclonic_untracked.nc
```
while the anticyclones had 3 files (as expected, since the tracks were too short).

On my side I think we can close the issue, 
thanks 🎉
