### ISSUE TITLE
Errors from add_uv() function from eddy detection linking to compute_stencil() function

### ISSUE THREAD

**Issue by boatwrva** [AntSimi/py-eddy-tracker#98]
Hi, 
I am trying to upload my netcdf4 file of SLA to use the eddy detection code. My dataset should be a regular grid (it's from a ROMS output). 
The code is having trouble at: 
g.add_uv("sla", "ugos", "vgos")
Here is the error code: 
![image](https://user-images.githubusercontent.com/67074485/124633564-63073280-de53-11eb-9d6b-0aab0e6c8435.png)
It tracks back to the compute_stencil() function in the add_uv() function, and the error message is 
"No matching definition for argument type(s) array(float64, 1d, C), array(float64, 1d, C), array(int16, 2d, F), bool, float64, bool, int64" 
I was able to run my code when I uploaded the ADT allsat med file (on this github page), so I compared it with my file and changed all of my data types to be the same type and the same size. However, the issue is still occurring. Please let me know what might be going wrong.

**Comment by boatwrva** [comment]
Also, up to the error, here is my code: 

!pip install numpy scipy netCDF4 matplotlib opencv-python pyyaml pint polygon3
!pip install pyEddyTracker

from datetime import datetime

from matplotlib import pyplot as plt
from py_eddy_tracker import data
from py_eddy_tracker.observations.observation import EddiesObservations
from py_eddy_tracker.dataset.grid import RegularGridDataset

def start_axes(title):
    fig = plt.figure(figsize=(13, 5))
    ax = fig.add_axes([0.03, 0.03, 0.90, 0.94])
    ax.set_xlim(-6, 36.5), ax.set_ylim(30, 46)
    ax.set_aspect("equal")
    ax.set_title(title)
    return ax


def update_axes(ax, mappable=None):
    ax.grid()
    if mappable:
        plt.colorbar(mappable, cax=ax.figure.add_axes([0.95, 0.05, 0.01, 0.9]))

fn = "/content/drive/MyDrive/Ocean/MAT_files/eddy_track/UCSC_sshandchloro_SLA.nc"
# their example dataset
# fn = "dt_med_allsat_phy_l4_2005T2.nc"

g = RegularGridDataset(fn,
    "lon",
    "lat",
)
 
g.add_uv("sla", "ugos", "vgos", 2)

**Comment by boatwrva** [comment]
Another note: my lat & lon coordinates are 1D arrays as data type 'float', just like that of the dt_med_allsat_phy... As well the time is 1D float and the SLA variable is a 3D array in data type int16 (just as the ADT is for the given dataset)

**Comment by AntSimi** [comment]
Some question:
- Could you describe the area of your grid?
- Did you have land on it? how land are set with nan or masked value?

Current method to add u/v want float32 or float64 for h in your case it's int16, It could be an evolution to do an automatic cast.
If you have already u/v field you don't need to do this step.

**Comment by boatwrva** [comment]
The area of my grid is -115.5 to -134 degrees east and 30 to 48 degrees north. It does go over land and the land is set with nan values I believe. I can try it changing the SSH to a float. I can download u/v but I don't have them right now. I can see if I can surpass the step without u/v, I didn't because I wasn't sure if it needed them as the code processes it particularly so that's good to know. I'll give an update after trying with the SLA as a float datatype.

**Comment by AntSimi** [comment]
you could force type like this before to compute add_uv:
```python
g.vars['sla'] = g.grid('sla').astype('f4')
```

I don't think you could use nan on int16?
Could you share the result of 
```bash
ncdump -h filename
```

**Comment by boatwrva** [comment]
You were right - I was not filling empty cells with NaNs. I also changed the data types to float64. Once I changed the FillValue to NaN and used your g.vars['sla'] = g.grid('sla').astype('f4') recommendation, I was able to get past that earlier error! 

However, I am now running into a different issue. 
When I run the code (I've been using SSH for ADT, which I think should be okay), the program seems to detect eddies (it displays that 46 anticyclonic eddies were detected and 49 cyclonic eddies were detected) but I doesn't display them (images below). This is true for both the SSH and SLA (which I calculated before making the nc file of the data) data. The SLA also seems to be working since it indicates that it has detected 58 cyclonic eddies and 49 anticyclonic eddies.  
Here is what is being plotted over the filtered plot: 

![image](https://user-images.githubusercontent.com/67074485/124823200-ebaecd00-df3e-11eb-8192-55e4f4a71f4e.png)

![image](https://user-images.githubusercontent.com/67074485/124812684-ed25c880-df31-11eb-9b21-efdfea40b927.png)

Here is the ouput of my ncdisp for the netcdf file:

Format:
           netcdf4
Dimensions:
           xi_rho  = 186
           eta_rho = 181
           s_rho   = 42
           time    = 3062
           xi_u    = 185
           eta_u   = 181
           xi_v    = 186
           eta_v   = 180
Variables:
    lon 
           Size:       186x1
           Dimensions: xi_rho
           Datatype:   double
           Attributes:
                       units = 'degrees_east'
    lat 
           Size:       181x1
           Dimensions: eta_rho
           Datatype:   double
           Attributes:
                       units = 'degrees_north'
    z   
           Size:       42x1
           Dimensions: s_rho
           Datatype:   double
    time
           Size:       3062x1
           Dimensions: time
           Datatype:   double
           Attributes:
                       _FillValue = NaN
                       units      = 'hours since 2013-01-01 00:00:00.000 UTC'
    ssh 
           Size:       186x181x3062
           Dimensions: xi_rho,eta_rho,time
           Datatype:   double
           Attributes:
                       _FillValue = NaN
                       units      = 'm'
    sla 
           Size:       186x181x3062
           Dimensions: xi_rho,eta_rho,time
           Datatype:   double
           Attributes:
                       _FillValue = NaN
                       units      = 'm'



Finally, you can also see my code at: https://colab.research.google.com/drive/1EcdngqP_A5LFityMpJV84ntm-lOL59Cm?usp=sharing

Let me know if there are any alterations I need to make to the data file or change something in the code!

**Comment by AntSimi** [comment]
Eddies longitude are cast between 0 to 360. So if you want display eddies with another range you need to use `ref` option. [Documentation is here](https://py-eddy-tracker.readthedocs.io/en/stable/_autosummary/py_eddy_tracker.observations.observation.EddiesObservations.html#py_eddy_tracker.observations.observation.EddiesObservations.display), in your case maybe set `ref=-180`.

**Comment by boatwrva** [comment]
Wow, thank you! this was hugely helpful!
